// Code generated by ent, DO NOT EDIT.

package paymentpurchasecounter

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentpurchasecounter type in the database.
	Label = "payment_purchase_counter"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProductType holds the string denoting the product_type field in the database.
	FieldProductType = "product_type"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldPeriodType holds the string denoting the period_type field in the database.
	FieldPeriodType = "period_type"
	// FieldPeriodStart holds the string denoting the period_start field in the database.
	FieldPeriodStart = "period_start"
	// FieldReservedCount holds the string denoting the reserved_count field in the database.
	FieldReservedCount = "reserved_count"
	// FieldConsumedCount holds the string denoting the consumed_count field in the database.
	FieldConsumedCount = "consumed_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentpurchasecounter in the database.
	Table = "payment_purchase_counters"
)

// Columns holds all SQL columns for paymentpurchasecounter fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldProductType,
	FieldProductID,
	FieldPeriodType,
	FieldPeriodStart,
	FieldReservedCount,
	FieldConsumedCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int64) error
	// ProductTypeValidator is a validator for the "product_type" field. It is called by the builders before save.
	ProductTypeValidator func(string) error
	// ProductIDValidator is a validator for the "product_id" field. It is called by the builders before save.
	ProductIDValidator func(int64) error
	// PeriodTypeValidator is a validator for the "period_type" field. It is called by the builders before save.
	PeriodTypeValidator func(string) error
	// DefaultReservedCount holds the default value on creation for the "reserved_count" field.
	DefaultReservedCount int
	// ReservedCountValidator is a validator for the "reserved_count" field. It is called by the builders before save.
	ReservedCountValidator func(int) error
	// DefaultConsumedCount holds the default value on creation for the "consumed_count" field.
	DefaultConsumedCount int
	// ConsumedCountValidator is a validator for the "consumed_count" field. It is called by the builders before save.
	ConsumedCountValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentPurchaseCounter queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByProductType orders the results by the product_type field.
func ByProductType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductType, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByPeriodType orders the results by the period_type field.
func ByPeriodType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodType, opts...).ToFunc()
}

// ByPeriodStart orders the results by the period_start field.
func ByPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodStart, opts...).ToFunc()
}

// ByReservedCount orders the results by the reserved_count field.
func ByReservedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedCount, opts...).ToFunc()
}

// ByConsumedCount orders the results by the consumed_count field.
func ByConsumedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumedCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
