// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/affiliaterebatejob"
)

// AffiliateRebateJob is the model entity for the AffiliateRebateJob schema.
type AffiliateRebateJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InviteeUserID holds the value of the "invitee_user_id" field.
	InviteeUserID int64 `json:"invitee_user_id,omitempty"`
	// SourceRedeemCodeID holds the value of the "source_redeem_code_id" field.
	SourceRedeemCodeID int64 `json:"source_redeem_code_id,omitempty"`
	// SourceKind holds the value of the "source_kind" field.
	SourceKind affiliaterebatejob.SourceKind `json:"source_kind,omitempty"`
	// BaseAmount holds the value of the "base_amount" field.
	BaseAmount float64 `json:"base_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status affiliaterebatejob.Status `json:"status,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// NextRetryAt holds the value of the "next_retry_at" field.
	NextRetryAt time.Time `json:"next_retry_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// LastErrorAt holds the value of the "last_error_at" field.
	LastErrorAt *time.Time `json:"last_error_at,omitempty"`
	// ProcessingStartedAt holds the value of the "processing_started_at" field.
	ProcessingStartedAt *time.Time `json:"processing_started_at,omitempty"`
	// SucceededAt holds the value of the "succeeded_at" field.
	SucceededAt *time.Time `json:"succeeded_at,omitempty"`
	// SkippedAt holds the value of the "skipped_at" field.
	SkippedAt *time.Time `json:"skipped_at,omitempty"`
	// FailedAt holds the value of the "failed_at" field.
	FailedAt *time.Time `json:"failed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AffiliateRebateJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case affiliaterebatejob.FieldBaseAmount:
			values[i] = new(sql.NullFloat64)
		case affiliaterebatejob.FieldID, affiliaterebatejob.FieldInviteeUserID, affiliaterebatejob.FieldSourceRedeemCodeID, affiliaterebatejob.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case affiliaterebatejob.FieldSourceKind, affiliaterebatejob.FieldStatus, affiliaterebatejob.FieldLastError:
			values[i] = new(sql.NullString)
		case affiliaterebatejob.FieldNextRetryAt, affiliaterebatejob.FieldLastErrorAt, affiliaterebatejob.FieldProcessingStartedAt, affiliaterebatejob.FieldSucceededAt, affiliaterebatejob.FieldSkippedAt, affiliaterebatejob.FieldFailedAt, affiliaterebatejob.FieldCreatedAt, affiliaterebatejob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AffiliateRebateJob fields.
func (_m *AffiliateRebateJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case affiliaterebatejob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case affiliaterebatejob.FieldInviteeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_user_id", values[i])
			} else if value.Valid {
				_m.InviteeUserID = value.Int64
			}
		case affiliaterebatejob.FieldSourceRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_redeem_code_id", values[i])
			} else if value.Valid {
				_m.SourceRedeemCodeID = value.Int64
			}
		case affiliaterebatejob.FieldSourceKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_kind", values[i])
			} else if value.Valid {
				_m.SourceKind = affiliaterebatejob.SourceKind(value.String)
			}
		case affiliaterebatejob.FieldBaseAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_amount", values[i])
			} else if value.Valid {
				_m.BaseAmount = value.Float64
			}
		case affiliaterebatejob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = affiliaterebatejob.Status(value.String)
			}
		case affiliaterebatejob.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case affiliaterebatejob.FieldNextRetryAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_retry_at", values[i])
			} else if value.Valid {
				_m.NextRetryAt = value.Time
			}
		case affiliaterebatejob.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case affiliaterebatejob.FieldLastErrorAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_at", values[i])
			} else if value.Valid {
				_m.LastErrorAt = new(time.Time)
				*_m.LastErrorAt = value.Time
			}
		case affiliaterebatejob.FieldProcessingStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processing_started_at", values[i])
			} else if value.Valid {
				_m.ProcessingStartedAt = new(time.Time)
				*_m.ProcessingStartedAt = value.Time
			}
		case affiliaterebatejob.FieldSucceededAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field succeeded_at", values[i])
			} else if value.Valid {
				_m.SucceededAt = new(time.Time)
				*_m.SucceededAt = value.Time
			}
		case affiliaterebatejob.FieldSkippedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field skipped_at", values[i])
			} else if value.Valid {
				_m.SkippedAt = new(time.Time)
				*_m.SkippedAt = value.Time
			}
		case affiliaterebatejob.FieldFailedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field failed_at", values[i])
			} else if value.Valid {
				_m.FailedAt = new(time.Time)
				*_m.FailedAt = value.Time
			}
		case affiliaterebatejob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case affiliaterebatejob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AffiliateRebateJob.
// This includes values selected through modifiers, order, etc.
func (_m *AffiliateRebateJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AffiliateRebateJob.
// Note that you need to call AffiliateRebateJob.Unwrap() before calling this method if this AffiliateRebateJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AffiliateRebateJob) Update() *AffiliateRebateJobUpdateOne {
	return NewAffiliateRebateJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AffiliateRebateJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AffiliateRebateJob) Unwrap() *AffiliateRebateJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AffiliateRebateJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AffiliateRebateJob) String() string {
	var builder strings.Builder
	builder.WriteString("AffiliateRebateJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invitee_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeUserID))
	builder.WriteString(", ")
	builder.WriteString("source_redeem_code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceRedeemCodeID))
	builder.WriteString(", ")
	builder.WriteString("source_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceKind))
	builder.WriteString(", ")
	builder.WriteString("base_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("next_retry_at=")
	builder.WriteString(_m.NextRetryAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastErrorAt; v != nil {
		builder.WriteString("last_error_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ProcessingStartedAt; v != nil {
		builder.WriteString("processing_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SucceededAt; v != nil {
		builder.WriteString("succeeded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SkippedAt; v != nil {
		builder.WriteString("skipped_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FailedAt; v != nil {
		builder.WriteString("failed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AffiliateRebateJobs is a parsable slice of AffiliateRebateJob.
type AffiliateRebateJobs []*AffiliateRebateJob
