// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/affiliaterebatejob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AffiliateRebateJobUpdate is the builder for updating AffiliateRebateJob entities.
type AffiliateRebateJobUpdate struct {
	config
	hooks    []Hook
	mutation *AffiliateRebateJobMutation
}

// Where appends a list predicates to the AffiliateRebateJobUpdate builder.
func (_u *AffiliateRebateJobUpdate) Where(ps ...predicate.AffiliateRebateJob) *AffiliateRebateJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AffiliateRebateJobUpdate) SetStatus(v affiliaterebatejob.Status) *AffiliateRebateJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdate) SetNillableStatus(v *affiliaterebatejob.Status) *AffiliateRebateJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *AffiliateRebateJobUpdate) SetAttempts(v int) *AffiliateRebateJobUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdate) SetNillableAttempts(v *int) *AffiliateRebateJobUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *AffiliateRebateJobUpdate) AddAttempts(v int) *AffiliateRebateJobUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *AffiliateRebateJobUpdate) SetNextRetryAt(v time.Time) *AffiliateRebateJobUpdate {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdate) SetNillableNextRetryAt(v *time.Time) *AffiliateRebateJobUpdate {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AffiliateRebateJobUpdate) SetLastError(v string) *AffiliateRebateJobUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdate) SetNillableLastError(v *string) *AffiliateRebateJobUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AffiliateRebateJobUpdate) ClearLastError() *AffiliateRebateJobUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastErrorAt sets the "last_error_at" field.
func (_u *AffiliateRebateJobUpdate) SetLastErrorAt(v time.Time) *AffiliateRebateJobUpdate {
	_u.mutation.SetLastErrorAt(v)
	return _u
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdate) SetNillableLastErrorAt(v *time.Time) *AffiliateRebateJobUpdate {
	if v != nil {
		_u.SetLastErrorAt(*v)
	}
	return _u
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (_u *AffiliateRebateJobUpdate) ClearLastErrorAt() *AffiliateRebateJobUpdate {
	_u.mutation.ClearLastErrorAt()
	return _u
}

// SetProcessingStartedAt sets the "processing_started_at" field.
func (_u *AffiliateRebateJobUpdate) SetProcessingStartedAt(v time.Time) *AffiliateRebateJobUpdate {
	_u.mutation.SetProcessingStartedAt(v)
	return _u
}

// SetNillableProcessingStartedAt sets the "processing_started_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdate) SetNillableProcessingStartedAt(v *time.Time) *AffiliateRebateJobUpdate {
	if v != nil {
		_u.SetProcessingStartedAt(*v)
	}
	return _u
}

// ClearProcessingStartedAt clears the value of the "processing_started_at" field.
func (_u *AffiliateRebateJobUpdate) ClearProcessingStartedAt() *AffiliateRebateJobUpdate {
	_u.mutation.ClearProcessingStartedAt()
	return _u
}

// SetSucceededAt sets the "succeeded_at" field.
func (_u *AffiliateRebateJobUpdate) SetSucceededAt(v time.Time) *AffiliateRebateJobUpdate {
	_u.mutation.SetSucceededAt(v)
	return _u
}

// SetNillableSucceededAt sets the "succeeded_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdate) SetNillableSucceededAt(v *time.Time) *AffiliateRebateJobUpdate {
	if v != nil {
		_u.SetSucceededAt(*v)
	}
	return _u
}

// ClearSucceededAt clears the value of the "succeeded_at" field.
func (_u *AffiliateRebateJobUpdate) ClearSucceededAt() *AffiliateRebateJobUpdate {
	_u.mutation.ClearSucceededAt()
	return _u
}

// SetSkippedAt sets the "skipped_at" field.
func (_u *AffiliateRebateJobUpdate) SetSkippedAt(v time.Time) *AffiliateRebateJobUpdate {
	_u.mutation.SetSkippedAt(v)
	return _u
}

// SetNillableSkippedAt sets the "skipped_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdate) SetNillableSkippedAt(v *time.Time) *AffiliateRebateJobUpdate {
	if v != nil {
		_u.SetSkippedAt(*v)
	}
	return _u
}

// ClearSkippedAt clears the value of the "skipped_at" field.
func (_u *AffiliateRebateJobUpdate) ClearSkippedAt() *AffiliateRebateJobUpdate {
	_u.mutation.ClearSkippedAt()
	return _u
}

// SetFailedAt sets the "failed_at" field.
func (_u *AffiliateRebateJobUpdate) SetFailedAt(v time.Time) *AffiliateRebateJobUpdate {
	_u.mutation.SetFailedAt(v)
	return _u
}

// SetNillableFailedAt sets the "failed_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdate) SetNillableFailedAt(v *time.Time) *AffiliateRebateJobUpdate {
	if v != nil {
		_u.SetFailedAt(*v)
	}
	return _u
}

// ClearFailedAt clears the value of the "failed_at" field.
func (_u *AffiliateRebateJobUpdate) ClearFailedAt() *AffiliateRebateJobUpdate {
	_u.mutation.ClearFailedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AffiliateRebateJobUpdate) SetUpdatedAt(v time.Time) *AffiliateRebateJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AffiliateRebateJobMutation object of the builder.
func (_u *AffiliateRebateJobUpdate) Mutation() *AffiliateRebateJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AffiliateRebateJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AffiliateRebateJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AffiliateRebateJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AffiliateRebateJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AffiliateRebateJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := affiliaterebatejob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AffiliateRebateJobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := affiliaterebatejob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AffiliateRebateJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempts(); ok {
		if err := affiliaterebatejob.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "AffiliateRebateJob.attempts": %w`, err)}
		}
	}
	return nil
}

func (_u *AffiliateRebateJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(affiliaterebatejob.Table, affiliaterebatejob.Columns, sqlgraph.NewFieldSpec(affiliaterebatejob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(affiliaterebatejob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(affiliaterebatejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(affiliaterebatejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldNextRetryAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(affiliaterebatejob.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(affiliaterebatejob.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldLastErrorAt, field.TypeTime, value)
	}
	if _u.mutation.LastErrorAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldLastErrorAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProcessingStartedAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldProcessingStartedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessingStartedAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldProcessingStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SucceededAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldSucceededAt, field.TypeTime, value)
	}
	if _u.mutation.SucceededAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldSucceededAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SkippedAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldSkippedAt, field.TypeTime, value)
	}
	if _u.mutation.SkippedAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldSkippedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldFailedAt, field.TypeTime, value)
	}
	if _u.mutation.FailedAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldFailedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{affiliaterebatejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AffiliateRebateJobUpdateOne is the builder for updating a single AffiliateRebateJob entity.
type AffiliateRebateJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AffiliateRebateJobMutation
}

// SetStatus sets the "status" field.
func (_u *AffiliateRebateJobUpdateOne) SetStatus(v affiliaterebatejob.Status) *AffiliateRebateJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdateOne) SetNillableStatus(v *affiliaterebatejob.Status) *AffiliateRebateJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *AffiliateRebateJobUpdateOne) SetAttempts(v int) *AffiliateRebateJobUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdateOne) SetNillableAttempts(v *int) *AffiliateRebateJobUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *AffiliateRebateJobUpdateOne) AddAttempts(v int) *AffiliateRebateJobUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *AffiliateRebateJobUpdateOne) SetNextRetryAt(v time.Time) *AffiliateRebateJobUpdateOne {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdateOne) SetNillableNextRetryAt(v *time.Time) *AffiliateRebateJobUpdateOne {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AffiliateRebateJobUpdateOne) SetLastError(v string) *AffiliateRebateJobUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdateOne) SetNillableLastError(v *string) *AffiliateRebateJobUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AffiliateRebateJobUpdateOne) ClearLastError() *AffiliateRebateJobUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastErrorAt sets the "last_error_at" field.
func (_u *AffiliateRebateJobUpdateOne) SetLastErrorAt(v time.Time) *AffiliateRebateJobUpdateOne {
	_u.mutation.SetLastErrorAt(v)
	return _u
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdateOne) SetNillableLastErrorAt(v *time.Time) *AffiliateRebateJobUpdateOne {
	if v != nil {
		_u.SetLastErrorAt(*v)
	}
	return _u
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (_u *AffiliateRebateJobUpdateOne) ClearLastErrorAt() *AffiliateRebateJobUpdateOne {
	_u.mutation.ClearLastErrorAt()
	return _u
}

// SetProcessingStartedAt sets the "processing_started_at" field.
func (_u *AffiliateRebateJobUpdateOne) SetProcessingStartedAt(v time.Time) *AffiliateRebateJobUpdateOne {
	_u.mutation.SetProcessingStartedAt(v)
	return _u
}

// SetNillableProcessingStartedAt sets the "processing_started_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdateOne) SetNillableProcessingStartedAt(v *time.Time) *AffiliateRebateJobUpdateOne {
	if v != nil {
		_u.SetProcessingStartedAt(*v)
	}
	return _u
}

// ClearProcessingStartedAt clears the value of the "processing_started_at" field.
func (_u *AffiliateRebateJobUpdateOne) ClearProcessingStartedAt() *AffiliateRebateJobUpdateOne {
	_u.mutation.ClearProcessingStartedAt()
	return _u
}

// SetSucceededAt sets the "succeeded_at" field.
func (_u *AffiliateRebateJobUpdateOne) SetSucceededAt(v time.Time) *AffiliateRebateJobUpdateOne {
	_u.mutation.SetSucceededAt(v)
	return _u
}

// SetNillableSucceededAt sets the "succeeded_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdateOne) SetNillableSucceededAt(v *time.Time) *AffiliateRebateJobUpdateOne {
	if v != nil {
		_u.SetSucceededAt(*v)
	}
	return _u
}

// ClearSucceededAt clears the value of the "succeeded_at" field.
func (_u *AffiliateRebateJobUpdateOne) ClearSucceededAt() *AffiliateRebateJobUpdateOne {
	_u.mutation.ClearSucceededAt()
	return _u
}

// SetSkippedAt sets the "skipped_at" field.
func (_u *AffiliateRebateJobUpdateOne) SetSkippedAt(v time.Time) *AffiliateRebateJobUpdateOne {
	_u.mutation.SetSkippedAt(v)
	return _u
}

// SetNillableSkippedAt sets the "skipped_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdateOne) SetNillableSkippedAt(v *time.Time) *AffiliateRebateJobUpdateOne {
	if v != nil {
		_u.SetSkippedAt(*v)
	}
	return _u
}

// ClearSkippedAt clears the value of the "skipped_at" field.
func (_u *AffiliateRebateJobUpdateOne) ClearSkippedAt() *AffiliateRebateJobUpdateOne {
	_u.mutation.ClearSkippedAt()
	return _u
}

// SetFailedAt sets the "failed_at" field.
func (_u *AffiliateRebateJobUpdateOne) SetFailedAt(v time.Time) *AffiliateRebateJobUpdateOne {
	_u.mutation.SetFailedAt(v)
	return _u
}

// SetNillableFailedAt sets the "failed_at" field if the given value is not nil.
func (_u *AffiliateRebateJobUpdateOne) SetNillableFailedAt(v *time.Time) *AffiliateRebateJobUpdateOne {
	if v != nil {
		_u.SetFailedAt(*v)
	}
	return _u
}

// ClearFailedAt clears the value of the "failed_at" field.
func (_u *AffiliateRebateJobUpdateOne) ClearFailedAt() *AffiliateRebateJobUpdateOne {
	_u.mutation.ClearFailedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AffiliateRebateJobUpdateOne) SetUpdatedAt(v time.Time) *AffiliateRebateJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AffiliateRebateJobMutation object of the builder.
func (_u *AffiliateRebateJobUpdateOne) Mutation() *AffiliateRebateJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the AffiliateRebateJobUpdate builder.
func (_u *AffiliateRebateJobUpdateOne) Where(ps ...predicate.AffiliateRebateJob) *AffiliateRebateJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AffiliateRebateJobUpdateOne) Select(field string, fields ...string) *AffiliateRebateJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AffiliateRebateJob entity.
func (_u *AffiliateRebateJobUpdateOne) Save(ctx context.Context) (*AffiliateRebateJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AffiliateRebateJobUpdateOne) SaveX(ctx context.Context) *AffiliateRebateJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AffiliateRebateJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AffiliateRebateJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AffiliateRebateJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := affiliaterebatejob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AffiliateRebateJobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := affiliaterebatejob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AffiliateRebateJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempts(); ok {
		if err := affiliaterebatejob.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "AffiliateRebateJob.attempts": %w`, err)}
		}
	}
	return nil
}

func (_u *AffiliateRebateJobUpdateOne) sqlSave(ctx context.Context) (_node *AffiliateRebateJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(affiliaterebatejob.Table, affiliaterebatejob.Columns, sqlgraph.NewFieldSpec(affiliaterebatejob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AffiliateRebateJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, affiliaterebatejob.FieldID)
		for _, f := range fields {
			if !affiliaterebatejob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != affiliaterebatejob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(affiliaterebatejob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(affiliaterebatejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(affiliaterebatejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldNextRetryAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(affiliaterebatejob.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(affiliaterebatejob.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldLastErrorAt, field.TypeTime, value)
	}
	if _u.mutation.LastErrorAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldLastErrorAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProcessingStartedAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldProcessingStartedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessingStartedAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldProcessingStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SucceededAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldSucceededAt, field.TypeTime, value)
	}
	if _u.mutation.SucceededAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldSucceededAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SkippedAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldSkippedAt, field.TypeTime, value)
	}
	if _u.mutation.SkippedAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldSkippedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldFailedAt, field.TypeTime, value)
	}
	if _u.mutation.FailedAtCleared() {
		_spec.ClearField(affiliaterebatejob.FieldFailedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(affiliaterebatejob.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AffiliateRebateJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{affiliaterebatejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
