// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/batchimagecredithold"
	"github.com/Wei-Shaw/sub2api/ent/batchimagecreditholdallocation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BatchImageCreditHoldUpdate is the builder for updating BatchImageCreditHold entities.
type BatchImageCreditHoldUpdate struct {
	config
	hooks    []Hook
	mutation *BatchImageCreditHoldMutation
}

// Where appends a list predicates to the BatchImageCreditHoldUpdate builder.
func (_u *BatchImageCreditHoldUpdate) Where(ps ...predicate.BatchImageCreditHold) *BatchImageCreditHoldUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *BatchImageCreditHoldUpdate) SetStatus(v batchimagecredithold.Status) *BatchImageCreditHoldUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdate) SetNillableStatus(v *batchimagecredithold.Status) *BatchImageCreditHoldUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCapturedAmount sets the "captured_amount" field.
func (_u *BatchImageCreditHoldUpdate) SetCapturedAmount(v float64) *BatchImageCreditHoldUpdate {
	_u.mutation.ResetCapturedAmount()
	_u.mutation.SetCapturedAmount(v)
	return _u
}

// SetNillableCapturedAmount sets the "captured_amount" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdate) SetNillableCapturedAmount(v *float64) *BatchImageCreditHoldUpdate {
	if v != nil {
		_u.SetCapturedAmount(*v)
	}
	return _u
}

// AddCapturedAmount adds value to the "captured_amount" field.
func (_u *BatchImageCreditHoldUpdate) AddCapturedAmount(v float64) *BatchImageCreditHoldUpdate {
	_u.mutation.AddCapturedAmount(v)
	return _u
}

// SetTemporaryCapturedAmount sets the "temporary_captured_amount" field.
func (_u *BatchImageCreditHoldUpdate) SetTemporaryCapturedAmount(v float64) *BatchImageCreditHoldUpdate {
	_u.mutation.ResetTemporaryCapturedAmount()
	_u.mutation.SetTemporaryCapturedAmount(v)
	return _u
}

// SetNillableTemporaryCapturedAmount sets the "temporary_captured_amount" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdate) SetNillableTemporaryCapturedAmount(v *float64) *BatchImageCreditHoldUpdate {
	if v != nil {
		_u.SetTemporaryCapturedAmount(*v)
	}
	return _u
}

// AddTemporaryCapturedAmount adds value to the "temporary_captured_amount" field.
func (_u *BatchImageCreditHoldUpdate) AddTemporaryCapturedAmount(v float64) *BatchImageCreditHoldUpdate {
	_u.mutation.AddTemporaryCapturedAmount(v)
	return _u
}

// SetPermanentCapturedAmount sets the "permanent_captured_amount" field.
func (_u *BatchImageCreditHoldUpdate) SetPermanentCapturedAmount(v float64) *BatchImageCreditHoldUpdate {
	_u.mutation.ResetPermanentCapturedAmount()
	_u.mutation.SetPermanentCapturedAmount(v)
	return _u
}

// SetNillablePermanentCapturedAmount sets the "permanent_captured_amount" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdate) SetNillablePermanentCapturedAmount(v *float64) *BatchImageCreditHoldUpdate {
	if v != nil {
		_u.SetPermanentCapturedAmount(*v)
	}
	return _u
}

// AddPermanentCapturedAmount adds value to the "permanent_captured_amount" field.
func (_u *BatchImageCreditHoldUpdate) AddPermanentCapturedAmount(v float64) *BatchImageCreditHoldUpdate {
	_u.mutation.AddPermanentCapturedAmount(v)
	return _u
}

// SetExpiredUnrestoredAmount sets the "expired_unrestored_amount" field.
func (_u *BatchImageCreditHoldUpdate) SetExpiredUnrestoredAmount(v float64) *BatchImageCreditHoldUpdate {
	_u.mutation.ResetExpiredUnrestoredAmount()
	_u.mutation.SetExpiredUnrestoredAmount(v)
	return _u
}

// SetNillableExpiredUnrestoredAmount sets the "expired_unrestored_amount" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdate) SetNillableExpiredUnrestoredAmount(v *float64) *BatchImageCreditHoldUpdate {
	if v != nil {
		_u.SetExpiredUnrestoredAmount(*v)
	}
	return _u
}

// AddExpiredUnrestoredAmount adds value to the "expired_unrestored_amount" field.
func (_u *BatchImageCreditHoldUpdate) AddExpiredUnrestoredAmount(v float64) *BatchImageCreditHoldUpdate {
	_u.mutation.AddExpiredUnrestoredAmount(v)
	return _u
}

// SetTerminalFingerprint sets the "terminal_fingerprint" field.
func (_u *BatchImageCreditHoldUpdate) SetTerminalFingerprint(v string) *BatchImageCreditHoldUpdate {
	_u.mutation.SetTerminalFingerprint(v)
	return _u
}

// SetNillableTerminalFingerprint sets the "terminal_fingerprint" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdate) SetNillableTerminalFingerprint(v *string) *BatchImageCreditHoldUpdate {
	if v != nil {
		_u.SetTerminalFingerprint(*v)
	}
	return _u
}

// ClearTerminalFingerprint clears the value of the "terminal_fingerprint" field.
func (_u *BatchImageCreditHoldUpdate) ClearTerminalFingerprint() *BatchImageCreditHoldUpdate {
	_u.mutation.ClearTerminalFingerprint()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *BatchImageCreditHoldUpdate) SetSettledAt(v time.Time) *BatchImageCreditHoldUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdate) SetNillableSettledAt(v *time.Time) *BatchImageCreditHoldUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *BatchImageCreditHoldUpdate) ClearSettledAt() *BatchImageCreditHoldUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BatchImageCreditHoldUpdate) SetUpdatedAt(v time.Time) *BatchImageCreditHoldUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAllocationIDs adds the "allocations" edge to the BatchImageCreditHoldAllocation entity by IDs.
func (_u *BatchImageCreditHoldUpdate) AddAllocationIDs(ids ...int64) *BatchImageCreditHoldUpdate {
	_u.mutation.AddAllocationIDs(ids...)
	return _u
}

// AddAllocations adds the "allocations" edges to the BatchImageCreditHoldAllocation entity.
func (_u *BatchImageCreditHoldUpdate) AddAllocations(v ...*BatchImageCreditHoldAllocation) *BatchImageCreditHoldUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllocationIDs(ids...)
}

// Mutation returns the BatchImageCreditHoldMutation object of the builder.
func (_u *BatchImageCreditHoldUpdate) Mutation() *BatchImageCreditHoldMutation {
	return _u.mutation
}

// ClearAllocations clears all "allocations" edges to the BatchImageCreditHoldAllocation entity.
func (_u *BatchImageCreditHoldUpdate) ClearAllocations() *BatchImageCreditHoldUpdate {
	_u.mutation.ClearAllocations()
	return _u
}

// RemoveAllocationIDs removes the "allocations" edge to BatchImageCreditHoldAllocation entities by IDs.
func (_u *BatchImageCreditHoldUpdate) RemoveAllocationIDs(ids ...int64) *BatchImageCreditHoldUpdate {
	_u.mutation.RemoveAllocationIDs(ids...)
	return _u
}

// RemoveAllocations removes "allocations" edges to BatchImageCreditHoldAllocation entities.
func (_u *BatchImageCreditHoldUpdate) RemoveAllocations(v ...*BatchImageCreditHoldAllocation) *BatchImageCreditHoldUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllocationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BatchImageCreditHoldUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BatchImageCreditHoldUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BatchImageCreditHoldUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BatchImageCreditHoldUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BatchImageCreditHoldUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := batchimagecredithold.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BatchImageCreditHoldUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := batchimagecredithold.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BatchImageCreditHold.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TerminalFingerprint(); ok {
		if err := batchimagecredithold.TerminalFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "terminal_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BatchImageCreditHold.terminal_fingerprint": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BatchImageCreditHold.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BatchImageCreditHold.api_key"`)
	}
	return nil
}

func (_u *BatchImageCreditHoldUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(batchimagecredithold.Table, batchimagecredithold.Columns, sqlgraph.NewFieldSpec(batchimagecredithold.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(batchimagecredithold.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CapturedAmount(); ok {
		_spec.SetField(batchimagecredithold.FieldCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCapturedAmount(); ok {
		_spec.AddField(batchimagecredithold.FieldCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TemporaryCapturedAmount(); ok {
		_spec.SetField(batchimagecredithold.FieldTemporaryCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemporaryCapturedAmount(); ok {
		_spec.AddField(batchimagecredithold.FieldTemporaryCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PermanentCapturedAmount(); ok {
		_spec.SetField(batchimagecredithold.FieldPermanentCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPermanentCapturedAmount(); ok {
		_spec.AddField(batchimagecredithold.FieldPermanentCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpiredUnrestoredAmount(); ok {
		_spec.SetField(batchimagecredithold.FieldExpiredUnrestoredAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExpiredUnrestoredAmount(); ok {
		_spec.AddField(batchimagecredithold.FieldExpiredUnrestoredAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TerminalFingerprint(); ok {
		_spec.SetField(batchimagecredithold.FieldTerminalFingerprint, field.TypeString, value)
	}
	if _u.mutation.TerminalFingerprintCleared() {
		_spec.ClearField(batchimagecredithold.FieldTerminalFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(batchimagecredithold.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(batchimagecredithold.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(batchimagecredithold.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   batchimagecredithold.AllocationsTable,
			Columns: []string{batchimagecredithold.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchimagecreditholdallocation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllocationsIDs(); len(nodes) > 0 && !_u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   batchimagecredithold.AllocationsTable,
			Columns: []string{batchimagecredithold.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchimagecreditholdallocation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   batchimagecredithold.AllocationsTable,
			Columns: []string{batchimagecredithold.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchimagecreditholdallocation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{batchimagecredithold.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BatchImageCreditHoldUpdateOne is the builder for updating a single BatchImageCreditHold entity.
type BatchImageCreditHoldUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BatchImageCreditHoldMutation
}

// SetStatus sets the "status" field.
func (_u *BatchImageCreditHoldUpdateOne) SetStatus(v batchimagecredithold.Status) *BatchImageCreditHoldUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdateOne) SetNillableStatus(v *batchimagecredithold.Status) *BatchImageCreditHoldUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCapturedAmount sets the "captured_amount" field.
func (_u *BatchImageCreditHoldUpdateOne) SetCapturedAmount(v float64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.ResetCapturedAmount()
	_u.mutation.SetCapturedAmount(v)
	return _u
}

// SetNillableCapturedAmount sets the "captured_amount" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdateOne) SetNillableCapturedAmount(v *float64) *BatchImageCreditHoldUpdateOne {
	if v != nil {
		_u.SetCapturedAmount(*v)
	}
	return _u
}

// AddCapturedAmount adds value to the "captured_amount" field.
func (_u *BatchImageCreditHoldUpdateOne) AddCapturedAmount(v float64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.AddCapturedAmount(v)
	return _u
}

// SetTemporaryCapturedAmount sets the "temporary_captured_amount" field.
func (_u *BatchImageCreditHoldUpdateOne) SetTemporaryCapturedAmount(v float64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.ResetTemporaryCapturedAmount()
	_u.mutation.SetTemporaryCapturedAmount(v)
	return _u
}

// SetNillableTemporaryCapturedAmount sets the "temporary_captured_amount" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdateOne) SetNillableTemporaryCapturedAmount(v *float64) *BatchImageCreditHoldUpdateOne {
	if v != nil {
		_u.SetTemporaryCapturedAmount(*v)
	}
	return _u
}

// AddTemporaryCapturedAmount adds value to the "temporary_captured_amount" field.
func (_u *BatchImageCreditHoldUpdateOne) AddTemporaryCapturedAmount(v float64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.AddTemporaryCapturedAmount(v)
	return _u
}

// SetPermanentCapturedAmount sets the "permanent_captured_amount" field.
func (_u *BatchImageCreditHoldUpdateOne) SetPermanentCapturedAmount(v float64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.ResetPermanentCapturedAmount()
	_u.mutation.SetPermanentCapturedAmount(v)
	return _u
}

// SetNillablePermanentCapturedAmount sets the "permanent_captured_amount" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdateOne) SetNillablePermanentCapturedAmount(v *float64) *BatchImageCreditHoldUpdateOne {
	if v != nil {
		_u.SetPermanentCapturedAmount(*v)
	}
	return _u
}

// AddPermanentCapturedAmount adds value to the "permanent_captured_amount" field.
func (_u *BatchImageCreditHoldUpdateOne) AddPermanentCapturedAmount(v float64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.AddPermanentCapturedAmount(v)
	return _u
}

// SetExpiredUnrestoredAmount sets the "expired_unrestored_amount" field.
func (_u *BatchImageCreditHoldUpdateOne) SetExpiredUnrestoredAmount(v float64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.ResetExpiredUnrestoredAmount()
	_u.mutation.SetExpiredUnrestoredAmount(v)
	return _u
}

// SetNillableExpiredUnrestoredAmount sets the "expired_unrestored_amount" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdateOne) SetNillableExpiredUnrestoredAmount(v *float64) *BatchImageCreditHoldUpdateOne {
	if v != nil {
		_u.SetExpiredUnrestoredAmount(*v)
	}
	return _u
}

// AddExpiredUnrestoredAmount adds value to the "expired_unrestored_amount" field.
func (_u *BatchImageCreditHoldUpdateOne) AddExpiredUnrestoredAmount(v float64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.AddExpiredUnrestoredAmount(v)
	return _u
}

// SetTerminalFingerprint sets the "terminal_fingerprint" field.
func (_u *BatchImageCreditHoldUpdateOne) SetTerminalFingerprint(v string) *BatchImageCreditHoldUpdateOne {
	_u.mutation.SetTerminalFingerprint(v)
	return _u
}

// SetNillableTerminalFingerprint sets the "terminal_fingerprint" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdateOne) SetNillableTerminalFingerprint(v *string) *BatchImageCreditHoldUpdateOne {
	if v != nil {
		_u.SetTerminalFingerprint(*v)
	}
	return _u
}

// ClearTerminalFingerprint clears the value of the "terminal_fingerprint" field.
func (_u *BatchImageCreditHoldUpdateOne) ClearTerminalFingerprint() *BatchImageCreditHoldUpdateOne {
	_u.mutation.ClearTerminalFingerprint()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *BatchImageCreditHoldUpdateOne) SetSettledAt(v time.Time) *BatchImageCreditHoldUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *BatchImageCreditHoldUpdateOne) SetNillableSettledAt(v *time.Time) *BatchImageCreditHoldUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *BatchImageCreditHoldUpdateOne) ClearSettledAt() *BatchImageCreditHoldUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BatchImageCreditHoldUpdateOne) SetUpdatedAt(v time.Time) *BatchImageCreditHoldUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAllocationIDs adds the "allocations" edge to the BatchImageCreditHoldAllocation entity by IDs.
func (_u *BatchImageCreditHoldUpdateOne) AddAllocationIDs(ids ...int64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.AddAllocationIDs(ids...)
	return _u
}

// AddAllocations adds the "allocations" edges to the BatchImageCreditHoldAllocation entity.
func (_u *BatchImageCreditHoldUpdateOne) AddAllocations(v ...*BatchImageCreditHoldAllocation) *BatchImageCreditHoldUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllocationIDs(ids...)
}

// Mutation returns the BatchImageCreditHoldMutation object of the builder.
func (_u *BatchImageCreditHoldUpdateOne) Mutation() *BatchImageCreditHoldMutation {
	return _u.mutation
}

// ClearAllocations clears all "allocations" edges to the BatchImageCreditHoldAllocation entity.
func (_u *BatchImageCreditHoldUpdateOne) ClearAllocations() *BatchImageCreditHoldUpdateOne {
	_u.mutation.ClearAllocations()
	return _u
}

// RemoveAllocationIDs removes the "allocations" edge to BatchImageCreditHoldAllocation entities by IDs.
func (_u *BatchImageCreditHoldUpdateOne) RemoveAllocationIDs(ids ...int64) *BatchImageCreditHoldUpdateOne {
	_u.mutation.RemoveAllocationIDs(ids...)
	return _u
}

// RemoveAllocations removes "allocations" edges to BatchImageCreditHoldAllocation entities.
func (_u *BatchImageCreditHoldUpdateOne) RemoveAllocations(v ...*BatchImageCreditHoldAllocation) *BatchImageCreditHoldUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllocationIDs(ids...)
}

// Where appends a list predicates to the BatchImageCreditHoldUpdate builder.
func (_u *BatchImageCreditHoldUpdateOne) Where(ps ...predicate.BatchImageCreditHold) *BatchImageCreditHoldUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BatchImageCreditHoldUpdateOne) Select(field string, fields ...string) *BatchImageCreditHoldUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BatchImageCreditHold entity.
func (_u *BatchImageCreditHoldUpdateOne) Save(ctx context.Context) (*BatchImageCreditHold, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BatchImageCreditHoldUpdateOne) SaveX(ctx context.Context) *BatchImageCreditHold {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BatchImageCreditHoldUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BatchImageCreditHoldUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BatchImageCreditHoldUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := batchimagecredithold.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BatchImageCreditHoldUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := batchimagecredithold.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BatchImageCreditHold.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TerminalFingerprint(); ok {
		if err := batchimagecredithold.TerminalFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "terminal_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BatchImageCreditHold.terminal_fingerprint": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BatchImageCreditHold.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BatchImageCreditHold.api_key"`)
	}
	return nil
}

func (_u *BatchImageCreditHoldUpdateOne) sqlSave(ctx context.Context) (_node *BatchImageCreditHold, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(batchimagecredithold.Table, batchimagecredithold.Columns, sqlgraph.NewFieldSpec(batchimagecredithold.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BatchImageCreditHold.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, batchimagecredithold.FieldID)
		for _, f := range fields {
			if !batchimagecredithold.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != batchimagecredithold.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(batchimagecredithold.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CapturedAmount(); ok {
		_spec.SetField(batchimagecredithold.FieldCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCapturedAmount(); ok {
		_spec.AddField(batchimagecredithold.FieldCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TemporaryCapturedAmount(); ok {
		_spec.SetField(batchimagecredithold.FieldTemporaryCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemporaryCapturedAmount(); ok {
		_spec.AddField(batchimagecredithold.FieldTemporaryCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PermanentCapturedAmount(); ok {
		_spec.SetField(batchimagecredithold.FieldPermanentCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPermanentCapturedAmount(); ok {
		_spec.AddField(batchimagecredithold.FieldPermanentCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpiredUnrestoredAmount(); ok {
		_spec.SetField(batchimagecredithold.FieldExpiredUnrestoredAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExpiredUnrestoredAmount(); ok {
		_spec.AddField(batchimagecredithold.FieldExpiredUnrestoredAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TerminalFingerprint(); ok {
		_spec.SetField(batchimagecredithold.FieldTerminalFingerprint, field.TypeString, value)
	}
	if _u.mutation.TerminalFingerprintCleared() {
		_spec.ClearField(batchimagecredithold.FieldTerminalFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(batchimagecredithold.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(batchimagecredithold.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(batchimagecredithold.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   batchimagecredithold.AllocationsTable,
			Columns: []string{batchimagecredithold.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchimagecreditholdallocation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllocationsIDs(); len(nodes) > 0 && !_u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   batchimagecredithold.AllocationsTable,
			Columns: []string{batchimagecredithold.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchimagecreditholdallocation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   batchimagecredithold.AllocationsTable,
			Columns: []string{batchimagecredithold.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchimagecreditholdallocation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BatchImageCreditHold{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{batchimagecredithold.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
