// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/currencyproduct"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CurrencyProductDelete is the builder for deleting a CurrencyProduct entity.
type CurrencyProductDelete struct {
	config
	hooks    []Hook
	mutation *CurrencyProductMutation
}

// Where appends a list predicates to the CurrencyProductDelete builder.
func (_d *CurrencyProductDelete) Where(ps ...predicate.CurrencyProduct) *CurrencyProductDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CurrencyProductDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CurrencyProductDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CurrencyProductDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(currencyproduct.Table, sqlgraph.NewFieldSpec(currencyproduct.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CurrencyProductDeleteOne is the builder for deleting a single CurrencyProduct entity.
type CurrencyProductDeleteOne struct {
	_d *CurrencyProductDelete
}

// Where appends a list predicates to the CurrencyProductDelete builder.
func (_d *CurrencyProductDeleteOne) Where(ps ...predicate.CurrencyProduct) *CurrencyProductDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CurrencyProductDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{currencyproduct.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CurrencyProductDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
