// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/currencyproduct"
)

// CurrencyProduct is the model entity for the CurrencyProduct schema.
type CurrencyProduct struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// PaymentPrice holds the value of the "payment_price" field.
	PaymentPrice float64 `json:"payment_price,omitempty"`
	// PaymentCreditType holds the value of the "payment_credit_type" field.
	PaymentCreditType string `json:"payment_credit_type,omitempty"`
	// CreditedType holds the value of the "credited_type" field.
	CreditedType string `json:"credited_type,omitempty"`
	// CreditedAmount holds the value of the "credited_amount" field.
	CreditedAmount float64 `json:"credited_amount,omitempty"`
	// CreditedPermanentAmount holds the value of the "credited_permanent_amount" field.
	CreditedPermanentAmount float64 `json:"credited_permanent_amount,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// ForSale holds the value of the "for_sale" field.
	ForSale bool `json:"for_sale,omitempty"`
	// DailyPurchaseLimit holds the value of the "daily_purchase_limit" field.
	DailyPurchaseLimit int `json:"daily_purchase_limit,omitempty"`
	// TotalPurchaseLimit holds the value of the "total_purchase_limit" field.
	TotalPurchaseLimit int `json:"total_purchase_limit,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CurrencyProduct) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case currencyproduct.FieldIsActive, currencyproduct.FieldForSale:
			values[i] = new(sql.NullBool)
		case currencyproduct.FieldPaymentPrice, currencyproduct.FieldCreditedAmount, currencyproduct.FieldCreditedPermanentAmount:
			values[i] = new(sql.NullFloat64)
		case currencyproduct.FieldID, currencyproduct.FieldSortOrder, currencyproduct.FieldDailyPurchaseLimit, currencyproduct.FieldTotalPurchaseLimit:
			values[i] = new(sql.NullInt64)
		case currencyproduct.FieldName, currencyproduct.FieldDescription, currencyproduct.FieldPaymentCreditType, currencyproduct.FieldCreditedType:
			values[i] = new(sql.NullString)
		case currencyproduct.FieldCreatedAt, currencyproduct.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CurrencyProduct fields.
func (_m *CurrencyProduct) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case currencyproduct.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case currencyproduct.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case currencyproduct.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case currencyproduct.FieldPaymentPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_price", values[i])
			} else if value.Valid {
				_m.PaymentPrice = value.Float64
			}
		case currencyproduct.FieldPaymentCreditType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_credit_type", values[i])
			} else if value.Valid {
				_m.PaymentCreditType = value.String
			}
		case currencyproduct.FieldCreditedType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credited_type", values[i])
			} else if value.Valid {
				_m.CreditedType = value.String
			}
		case currencyproduct.FieldCreditedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credited_amount", values[i])
			} else if value.Valid {
				_m.CreditedAmount = value.Float64
			}
		case currencyproduct.FieldCreditedPermanentAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credited_permanent_amount", values[i])
			} else if value.Valid {
				_m.CreditedPermanentAmount = value.Float64
			}
		case currencyproduct.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case currencyproduct.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case currencyproduct.FieldForSale:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field for_sale", values[i])
			} else if value.Valid {
				_m.ForSale = value.Bool
			}
		case currencyproduct.FieldDailyPurchaseLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_purchase_limit", values[i])
			} else if value.Valid {
				_m.DailyPurchaseLimit = int(value.Int64)
			}
		case currencyproduct.FieldTotalPurchaseLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_purchase_limit", values[i])
			} else if value.Valid {
				_m.TotalPurchaseLimit = int(value.Int64)
			}
		case currencyproduct.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case currencyproduct.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CurrencyProduct.
// This includes values selected through modifiers, order, etc.
func (_m *CurrencyProduct) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CurrencyProduct.
// Note that you need to call CurrencyProduct.Unwrap() before calling this method if this CurrencyProduct
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CurrencyProduct) Update() *CurrencyProductUpdateOne {
	return NewCurrencyProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CurrencyProduct entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CurrencyProduct) Unwrap() *CurrencyProduct {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CurrencyProduct is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CurrencyProduct) String() string {
	var builder strings.Builder
	builder.WriteString("CurrencyProduct(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("payment_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentPrice))
	builder.WriteString(", ")
	builder.WriteString("payment_credit_type=")
	builder.WriteString(_m.PaymentCreditType)
	builder.WriteString(", ")
	builder.WriteString("credited_type=")
	builder.WriteString(_m.CreditedType)
	builder.WriteString(", ")
	builder.WriteString("credited_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditedAmount))
	builder.WriteString(", ")
	builder.WriteString("credited_permanent_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditedPermanentAmount))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("for_sale=")
	builder.WriteString(fmt.Sprintf("%v", _m.ForSale))
	builder.WriteString(", ")
	builder.WriteString("daily_purchase_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyPurchaseLimit))
	builder.WriteString(", ")
	builder.WriteString("total_purchase_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalPurchaseLimit))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CurrencyProducts is a parsable slice of CurrencyProduct.
type CurrencyProducts []*CurrencyProduct
