// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/currencyproduct"
)

// CurrencyProductCreate is the builder for creating a CurrencyProduct entity.
type CurrencyProductCreate struct {
	config
	mutation *CurrencyProductMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *CurrencyProductCreate) SetName(v string) *CurrencyProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CurrencyProductCreate) SetDescription(v string) *CurrencyProductCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillableDescription(v *string) *CurrencyProductCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPaymentPrice sets the "payment_price" field.
func (_c *CurrencyProductCreate) SetPaymentPrice(v float64) *CurrencyProductCreate {
	_c.mutation.SetPaymentPrice(v)
	return _c
}

// SetPaymentCreditType sets the "payment_credit_type" field.
func (_c *CurrencyProductCreate) SetPaymentCreditType(v string) *CurrencyProductCreate {
	_c.mutation.SetPaymentCreditType(v)
	return _c
}

// SetNillablePaymentCreditType sets the "payment_credit_type" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillablePaymentCreditType(v *string) *CurrencyProductCreate {
	if v != nil {
		_c.SetPaymentCreditType(*v)
	}
	return _c
}

// SetCreditedType sets the "credited_type" field.
func (_c *CurrencyProductCreate) SetCreditedType(v string) *CurrencyProductCreate {
	_c.mutation.SetCreditedType(v)
	return _c
}

// SetNillableCreditedType sets the "credited_type" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillableCreditedType(v *string) *CurrencyProductCreate {
	if v != nil {
		_c.SetCreditedType(*v)
	}
	return _c
}

// SetCreditedAmount sets the "credited_amount" field.
func (_c *CurrencyProductCreate) SetCreditedAmount(v float64) *CurrencyProductCreate {
	_c.mutation.SetCreditedAmount(v)
	return _c
}

// SetCreditedPermanentAmount sets the "credited_permanent_amount" field.
func (_c *CurrencyProductCreate) SetCreditedPermanentAmount(v float64) *CurrencyProductCreate {
	_c.mutation.SetCreditedPermanentAmount(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *CurrencyProductCreate) SetSortOrder(v int) *CurrencyProductCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillableSortOrder(v *int) *CurrencyProductCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *CurrencyProductCreate) SetIsActive(v bool) *CurrencyProductCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillableIsActive(v *bool) *CurrencyProductCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetForSale sets the "for_sale" field.
func (_c *CurrencyProductCreate) SetForSale(v bool) *CurrencyProductCreate {
	_c.mutation.SetForSale(v)
	return _c
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillableForSale(v *bool) *CurrencyProductCreate {
	if v != nil {
		_c.SetForSale(*v)
	}
	return _c
}

// SetDailyPurchaseLimit sets the "daily_purchase_limit" field.
func (_c *CurrencyProductCreate) SetDailyPurchaseLimit(v int) *CurrencyProductCreate {
	_c.mutation.SetDailyPurchaseLimit(v)
	return _c
}

// SetNillableDailyPurchaseLimit sets the "daily_purchase_limit" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillableDailyPurchaseLimit(v *int) *CurrencyProductCreate {
	if v != nil {
		_c.SetDailyPurchaseLimit(*v)
	}
	return _c
}

// SetTotalPurchaseLimit sets the "total_purchase_limit" field.
func (_c *CurrencyProductCreate) SetTotalPurchaseLimit(v int) *CurrencyProductCreate {
	_c.mutation.SetTotalPurchaseLimit(v)
	return _c
}

// SetNillableTotalPurchaseLimit sets the "total_purchase_limit" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillableTotalPurchaseLimit(v *int) *CurrencyProductCreate {
	if v != nil {
		_c.SetTotalPurchaseLimit(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CurrencyProductCreate) SetCreatedAt(v time.Time) *CurrencyProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillableCreatedAt(v *time.Time) *CurrencyProductCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CurrencyProductCreate) SetUpdatedAt(v time.Time) *CurrencyProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CurrencyProductCreate) SetNillableUpdatedAt(v *time.Time) *CurrencyProductCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CurrencyProductMutation object of the builder.
func (_c *CurrencyProductCreate) Mutation() *CurrencyProductMutation {
	return _c.mutation
}

// Save creates the CurrencyProduct in the database.
func (_c *CurrencyProductCreate) Save(ctx context.Context) (*CurrencyProduct, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CurrencyProductCreate) SaveX(ctx context.Context) *CurrencyProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CurrencyProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CurrencyProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CurrencyProductCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := currencyproduct.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.PaymentCreditType(); !ok {
		v := currencyproduct.DefaultPaymentCreditType
		_c.mutation.SetPaymentCreditType(v)
	}
	if _, ok := _c.mutation.CreditedType(); !ok {
		v := currencyproduct.DefaultCreditedType
		_c.mutation.SetCreditedType(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := currencyproduct.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := currencyproduct.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		v := currencyproduct.DefaultForSale
		_c.mutation.SetForSale(v)
	}
	if _, ok := _c.mutation.DailyPurchaseLimit(); !ok {
		v := currencyproduct.DefaultDailyPurchaseLimit
		_c.mutation.SetDailyPurchaseLimit(v)
	}
	if _, ok := _c.mutation.TotalPurchaseLimit(); !ok {
		v := currencyproduct.DefaultTotalPurchaseLimit
		_c.mutation.SetTotalPurchaseLimit(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := currencyproduct.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := currencyproduct.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CurrencyProductCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CurrencyProduct.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := currencyproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CurrencyProduct.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "CurrencyProduct.description"`)}
	}
	if _, ok := _c.mutation.PaymentPrice(); !ok {
		return &ValidationError{Name: "payment_price", err: errors.New(`ent: missing required field "CurrencyProduct.payment_price"`)}
	}
	if _, ok := _c.mutation.PaymentCreditType(); !ok {
		return &ValidationError{Name: "payment_credit_type", err: errors.New(`ent: missing required field "CurrencyProduct.payment_credit_type"`)}
	}
	if v, ok := _c.mutation.PaymentCreditType(); ok {
		if err := currencyproduct.PaymentCreditTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_credit_type", err: fmt.Errorf(`ent: validator failed for field "CurrencyProduct.payment_credit_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreditedType(); !ok {
		return &ValidationError{Name: "credited_type", err: errors.New(`ent: missing required field "CurrencyProduct.credited_type"`)}
	}
	if v, ok := _c.mutation.CreditedType(); ok {
		if err := currencyproduct.CreditedTypeValidator(v); err != nil {
			return &ValidationError{Name: "credited_type", err: fmt.Errorf(`ent: validator failed for field "CurrencyProduct.credited_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreditedAmount(); !ok {
		return &ValidationError{Name: "credited_amount", err: errors.New(`ent: missing required field "CurrencyProduct.credited_amount"`)}
	}
	if _, ok := _c.mutation.CreditedPermanentAmount(); !ok {
		return &ValidationError{Name: "credited_permanent_amount", err: errors.New(`ent: missing required field "CurrencyProduct.credited_permanent_amount"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "CurrencyProduct.sort_order"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "CurrencyProduct.is_active"`)}
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		return &ValidationError{Name: "for_sale", err: errors.New(`ent: missing required field "CurrencyProduct.for_sale"`)}
	}
	if _, ok := _c.mutation.DailyPurchaseLimit(); !ok {
		return &ValidationError{Name: "daily_purchase_limit", err: errors.New(`ent: missing required field "CurrencyProduct.daily_purchase_limit"`)}
	}
	if v, ok := _c.mutation.DailyPurchaseLimit(); ok {
		if err := currencyproduct.DailyPurchaseLimitValidator(v); err != nil {
			return &ValidationError{Name: "daily_purchase_limit", err: fmt.Errorf(`ent: validator failed for field "CurrencyProduct.daily_purchase_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalPurchaseLimit(); !ok {
		return &ValidationError{Name: "total_purchase_limit", err: errors.New(`ent: missing required field "CurrencyProduct.total_purchase_limit"`)}
	}
	if v, ok := _c.mutation.TotalPurchaseLimit(); ok {
		if err := currencyproduct.TotalPurchaseLimitValidator(v); err != nil {
			return &ValidationError{Name: "total_purchase_limit", err: fmt.Errorf(`ent: validator failed for field "CurrencyProduct.total_purchase_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CurrencyProduct.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CurrencyProduct.updated_at"`)}
	}
	return nil
}

func (_c *CurrencyProductCreate) sqlSave(ctx context.Context) (*CurrencyProduct, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CurrencyProductCreate) createSpec() (*CurrencyProduct, *sqlgraph.CreateSpec) {
	var (
		_node = &CurrencyProduct{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(currencyproduct.Table, sqlgraph.NewFieldSpec(currencyproduct.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(currencyproduct.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(currencyproduct.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PaymentPrice(); ok {
		_spec.SetField(currencyproduct.FieldPaymentPrice, field.TypeFloat64, value)
		_node.PaymentPrice = value
	}
	if value, ok := _c.mutation.PaymentCreditType(); ok {
		_spec.SetField(currencyproduct.FieldPaymentCreditType, field.TypeString, value)
		_node.PaymentCreditType = value
	}
	if value, ok := _c.mutation.CreditedType(); ok {
		_spec.SetField(currencyproduct.FieldCreditedType, field.TypeString, value)
		_node.CreditedType = value
	}
	if value, ok := _c.mutation.CreditedAmount(); ok {
		_spec.SetField(currencyproduct.FieldCreditedAmount, field.TypeFloat64, value)
		_node.CreditedAmount = value
	}
	if value, ok := _c.mutation.CreditedPermanentAmount(); ok {
		_spec.SetField(currencyproduct.FieldCreditedPermanentAmount, field.TypeFloat64, value)
		_node.CreditedPermanentAmount = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(currencyproduct.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(currencyproduct.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.ForSale(); ok {
		_spec.SetField(currencyproduct.FieldForSale, field.TypeBool, value)
		_node.ForSale = value
	}
	if value, ok := _c.mutation.DailyPurchaseLimit(); ok {
		_spec.SetField(currencyproduct.FieldDailyPurchaseLimit, field.TypeInt, value)
		_node.DailyPurchaseLimit = value
	}
	if value, ok := _c.mutation.TotalPurchaseLimit(); ok {
		_spec.SetField(currencyproduct.FieldTotalPurchaseLimit, field.TypeInt, value)
		_node.TotalPurchaseLimit = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(currencyproduct.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(currencyproduct.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CurrencyProduct.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CurrencyProductUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CurrencyProductCreate) OnConflict(opts ...sql.ConflictOption) *CurrencyProductUpsertOne {
	_c.conflict = opts
	return &CurrencyProductUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CurrencyProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CurrencyProductCreate) OnConflictColumns(columns ...string) *CurrencyProductUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CurrencyProductUpsertOne{
		create: _c,
	}
}

type (
	// CurrencyProductUpsertOne is the builder for "upsert"-ing
	//  one CurrencyProduct node.
	CurrencyProductUpsertOne struct {
		create *CurrencyProductCreate
	}

	// CurrencyProductUpsert is the "OnConflict" setter.
	CurrencyProductUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *CurrencyProductUpsert) SetName(v string) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateName() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *CurrencyProductUpsert) SetDescription(v string) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateDescription() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldDescription)
	return u
}

// SetPaymentPrice sets the "payment_price" field.
func (u *CurrencyProductUpsert) SetPaymentPrice(v float64) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldPaymentPrice, v)
	return u
}

// UpdatePaymentPrice sets the "payment_price" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdatePaymentPrice() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldPaymentPrice)
	return u
}

// AddPaymentPrice adds v to the "payment_price" field.
func (u *CurrencyProductUpsert) AddPaymentPrice(v float64) *CurrencyProductUpsert {
	u.Add(currencyproduct.FieldPaymentPrice, v)
	return u
}

// SetPaymentCreditType sets the "payment_credit_type" field.
func (u *CurrencyProductUpsert) SetPaymentCreditType(v string) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldPaymentCreditType, v)
	return u
}

// UpdatePaymentCreditType sets the "payment_credit_type" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdatePaymentCreditType() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldPaymentCreditType)
	return u
}

// SetCreditedType sets the "credited_type" field.
func (u *CurrencyProductUpsert) SetCreditedType(v string) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldCreditedType, v)
	return u
}

// UpdateCreditedType sets the "credited_type" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateCreditedType() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldCreditedType)
	return u
}

// SetCreditedAmount sets the "credited_amount" field.
func (u *CurrencyProductUpsert) SetCreditedAmount(v float64) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldCreditedAmount, v)
	return u
}

// UpdateCreditedAmount sets the "credited_amount" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateCreditedAmount() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldCreditedAmount)
	return u
}

// AddCreditedAmount adds v to the "credited_amount" field.
func (u *CurrencyProductUpsert) AddCreditedAmount(v float64) *CurrencyProductUpsert {
	u.Add(currencyproduct.FieldCreditedAmount, v)
	return u
}

// SetCreditedPermanentAmount sets the "credited_permanent_amount" field.
func (u *CurrencyProductUpsert) SetCreditedPermanentAmount(v float64) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldCreditedPermanentAmount, v)
	return u
}

// UpdateCreditedPermanentAmount sets the "credited_permanent_amount" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateCreditedPermanentAmount() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldCreditedPermanentAmount)
	return u
}

// AddCreditedPermanentAmount adds v to the "credited_permanent_amount" field.
func (u *CurrencyProductUpsert) AddCreditedPermanentAmount(v float64) *CurrencyProductUpsert {
	u.Add(currencyproduct.FieldCreditedPermanentAmount, v)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *CurrencyProductUpsert) SetSortOrder(v int) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateSortOrder() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CurrencyProductUpsert) AddSortOrder(v int) *CurrencyProductUpsert {
	u.Add(currencyproduct.FieldSortOrder, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *CurrencyProductUpsert) SetIsActive(v bool) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateIsActive() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldIsActive)
	return u
}

// SetForSale sets the "for_sale" field.
func (u *CurrencyProductUpsert) SetForSale(v bool) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldForSale, v)
	return u
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateForSale() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldForSale)
	return u
}

// SetDailyPurchaseLimit sets the "daily_purchase_limit" field.
func (u *CurrencyProductUpsert) SetDailyPurchaseLimit(v int) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldDailyPurchaseLimit, v)
	return u
}

// UpdateDailyPurchaseLimit sets the "daily_purchase_limit" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateDailyPurchaseLimit() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldDailyPurchaseLimit)
	return u
}

// AddDailyPurchaseLimit adds v to the "daily_purchase_limit" field.
func (u *CurrencyProductUpsert) AddDailyPurchaseLimit(v int) *CurrencyProductUpsert {
	u.Add(currencyproduct.FieldDailyPurchaseLimit, v)
	return u
}

// SetTotalPurchaseLimit sets the "total_purchase_limit" field.
func (u *CurrencyProductUpsert) SetTotalPurchaseLimit(v int) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldTotalPurchaseLimit, v)
	return u
}

// UpdateTotalPurchaseLimit sets the "total_purchase_limit" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateTotalPurchaseLimit() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldTotalPurchaseLimit)
	return u
}

// AddTotalPurchaseLimit adds v to the "total_purchase_limit" field.
func (u *CurrencyProductUpsert) AddTotalPurchaseLimit(v int) *CurrencyProductUpsert {
	u.Add(currencyproduct.FieldTotalPurchaseLimit, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CurrencyProductUpsert) SetUpdatedAt(v time.Time) *CurrencyProductUpsert {
	u.Set(currencyproduct.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CurrencyProductUpsert) UpdateUpdatedAt() *CurrencyProductUpsert {
	u.SetExcluded(currencyproduct.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CurrencyProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CurrencyProductUpsertOne) UpdateNewValues() *CurrencyProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(currencyproduct.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CurrencyProduct.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CurrencyProductUpsertOne) Ignore() *CurrencyProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CurrencyProductUpsertOne) DoNothing() *CurrencyProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CurrencyProductCreate.OnConflict
// documentation for more info.
func (u *CurrencyProductUpsertOne) Update(set func(*CurrencyProductUpsert)) *CurrencyProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CurrencyProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CurrencyProductUpsertOne) SetName(v string) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateName() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *CurrencyProductUpsertOne) SetDescription(v string) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateDescription() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateDescription()
	})
}

// SetPaymentPrice sets the "payment_price" field.
func (u *CurrencyProductUpsertOne) SetPaymentPrice(v float64) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetPaymentPrice(v)
	})
}

// AddPaymentPrice adds v to the "payment_price" field.
func (u *CurrencyProductUpsertOne) AddPaymentPrice(v float64) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddPaymentPrice(v)
	})
}

// UpdatePaymentPrice sets the "payment_price" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdatePaymentPrice() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdatePaymentPrice()
	})
}

// SetPaymentCreditType sets the "payment_credit_type" field.
func (u *CurrencyProductUpsertOne) SetPaymentCreditType(v string) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetPaymentCreditType(v)
	})
}

// UpdatePaymentCreditType sets the "payment_credit_type" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdatePaymentCreditType() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdatePaymentCreditType()
	})
}

// SetCreditedType sets the "credited_type" field.
func (u *CurrencyProductUpsertOne) SetCreditedType(v string) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetCreditedType(v)
	})
}

// UpdateCreditedType sets the "credited_type" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateCreditedType() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateCreditedType()
	})
}

// SetCreditedAmount sets the "credited_amount" field.
func (u *CurrencyProductUpsertOne) SetCreditedAmount(v float64) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetCreditedAmount(v)
	})
}

// AddCreditedAmount adds v to the "credited_amount" field.
func (u *CurrencyProductUpsertOne) AddCreditedAmount(v float64) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddCreditedAmount(v)
	})
}

// UpdateCreditedAmount sets the "credited_amount" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateCreditedAmount() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateCreditedAmount()
	})
}

// SetCreditedPermanentAmount sets the "credited_permanent_amount" field.
func (u *CurrencyProductUpsertOne) SetCreditedPermanentAmount(v float64) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetCreditedPermanentAmount(v)
	})
}

// AddCreditedPermanentAmount adds v to the "credited_permanent_amount" field.
func (u *CurrencyProductUpsertOne) AddCreditedPermanentAmount(v float64) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddCreditedPermanentAmount(v)
	})
}

// UpdateCreditedPermanentAmount sets the "credited_permanent_amount" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateCreditedPermanentAmount() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateCreditedPermanentAmount()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CurrencyProductUpsertOne) SetSortOrder(v int) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CurrencyProductUpsertOne) AddSortOrder(v int) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateSortOrder() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsActive sets the "is_active" field.
func (u *CurrencyProductUpsertOne) SetIsActive(v bool) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateIsActive() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateIsActive()
	})
}

// SetForSale sets the "for_sale" field.
func (u *CurrencyProductUpsertOne) SetForSale(v bool) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateForSale() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateForSale()
	})
}

// SetDailyPurchaseLimit sets the "daily_purchase_limit" field.
func (u *CurrencyProductUpsertOne) SetDailyPurchaseLimit(v int) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetDailyPurchaseLimit(v)
	})
}

// AddDailyPurchaseLimit adds v to the "daily_purchase_limit" field.
func (u *CurrencyProductUpsertOne) AddDailyPurchaseLimit(v int) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddDailyPurchaseLimit(v)
	})
}

// UpdateDailyPurchaseLimit sets the "daily_purchase_limit" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateDailyPurchaseLimit() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateDailyPurchaseLimit()
	})
}

// SetTotalPurchaseLimit sets the "total_purchase_limit" field.
func (u *CurrencyProductUpsertOne) SetTotalPurchaseLimit(v int) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetTotalPurchaseLimit(v)
	})
}

// AddTotalPurchaseLimit adds v to the "total_purchase_limit" field.
func (u *CurrencyProductUpsertOne) AddTotalPurchaseLimit(v int) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddTotalPurchaseLimit(v)
	})
}

// UpdateTotalPurchaseLimit sets the "total_purchase_limit" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateTotalPurchaseLimit() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateTotalPurchaseLimit()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CurrencyProductUpsertOne) SetUpdatedAt(v time.Time) *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CurrencyProductUpsertOne) UpdateUpdatedAt() *CurrencyProductUpsertOne {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CurrencyProductUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CurrencyProductCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CurrencyProductUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CurrencyProductUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CurrencyProductUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CurrencyProductCreateBulk is the builder for creating many CurrencyProduct entities in bulk.
type CurrencyProductCreateBulk struct {
	config
	err      error
	builders []*CurrencyProductCreate
	conflict []sql.ConflictOption
}

// Save creates the CurrencyProduct entities in the database.
func (_c *CurrencyProductCreateBulk) Save(ctx context.Context) ([]*CurrencyProduct, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CurrencyProduct, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CurrencyProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CurrencyProductCreateBulk) SaveX(ctx context.Context) []*CurrencyProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CurrencyProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CurrencyProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CurrencyProduct.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CurrencyProductUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CurrencyProductCreateBulk) OnConflict(opts ...sql.ConflictOption) *CurrencyProductUpsertBulk {
	_c.conflict = opts
	return &CurrencyProductUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CurrencyProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CurrencyProductCreateBulk) OnConflictColumns(columns ...string) *CurrencyProductUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CurrencyProductUpsertBulk{
		create: _c,
	}
}

// CurrencyProductUpsertBulk is the builder for "upsert"-ing
// a bulk of CurrencyProduct nodes.
type CurrencyProductUpsertBulk struct {
	create *CurrencyProductCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CurrencyProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CurrencyProductUpsertBulk) UpdateNewValues() *CurrencyProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(currencyproduct.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CurrencyProduct.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CurrencyProductUpsertBulk) Ignore() *CurrencyProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CurrencyProductUpsertBulk) DoNothing() *CurrencyProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CurrencyProductCreateBulk.OnConflict
// documentation for more info.
func (u *CurrencyProductUpsertBulk) Update(set func(*CurrencyProductUpsert)) *CurrencyProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CurrencyProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CurrencyProductUpsertBulk) SetName(v string) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateName() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *CurrencyProductUpsertBulk) SetDescription(v string) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateDescription() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateDescription()
	})
}

// SetPaymentPrice sets the "payment_price" field.
func (u *CurrencyProductUpsertBulk) SetPaymentPrice(v float64) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetPaymentPrice(v)
	})
}

// AddPaymentPrice adds v to the "payment_price" field.
func (u *CurrencyProductUpsertBulk) AddPaymentPrice(v float64) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddPaymentPrice(v)
	})
}

// UpdatePaymentPrice sets the "payment_price" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdatePaymentPrice() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdatePaymentPrice()
	})
}

// SetPaymentCreditType sets the "payment_credit_type" field.
func (u *CurrencyProductUpsertBulk) SetPaymentCreditType(v string) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetPaymentCreditType(v)
	})
}

// UpdatePaymentCreditType sets the "payment_credit_type" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdatePaymentCreditType() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdatePaymentCreditType()
	})
}

// SetCreditedType sets the "credited_type" field.
func (u *CurrencyProductUpsertBulk) SetCreditedType(v string) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetCreditedType(v)
	})
}

// UpdateCreditedType sets the "credited_type" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateCreditedType() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateCreditedType()
	})
}

// SetCreditedAmount sets the "credited_amount" field.
func (u *CurrencyProductUpsertBulk) SetCreditedAmount(v float64) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetCreditedAmount(v)
	})
}

// AddCreditedAmount adds v to the "credited_amount" field.
func (u *CurrencyProductUpsertBulk) AddCreditedAmount(v float64) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddCreditedAmount(v)
	})
}

// UpdateCreditedAmount sets the "credited_amount" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateCreditedAmount() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateCreditedAmount()
	})
}

// SetCreditedPermanentAmount sets the "credited_permanent_amount" field.
func (u *CurrencyProductUpsertBulk) SetCreditedPermanentAmount(v float64) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetCreditedPermanentAmount(v)
	})
}

// AddCreditedPermanentAmount adds v to the "credited_permanent_amount" field.
func (u *CurrencyProductUpsertBulk) AddCreditedPermanentAmount(v float64) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddCreditedPermanentAmount(v)
	})
}

// UpdateCreditedPermanentAmount sets the "credited_permanent_amount" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateCreditedPermanentAmount() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateCreditedPermanentAmount()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CurrencyProductUpsertBulk) SetSortOrder(v int) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CurrencyProductUpsertBulk) AddSortOrder(v int) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateSortOrder() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsActive sets the "is_active" field.
func (u *CurrencyProductUpsertBulk) SetIsActive(v bool) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateIsActive() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateIsActive()
	})
}

// SetForSale sets the "for_sale" field.
func (u *CurrencyProductUpsertBulk) SetForSale(v bool) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateForSale() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateForSale()
	})
}

// SetDailyPurchaseLimit sets the "daily_purchase_limit" field.
func (u *CurrencyProductUpsertBulk) SetDailyPurchaseLimit(v int) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetDailyPurchaseLimit(v)
	})
}

// AddDailyPurchaseLimit adds v to the "daily_purchase_limit" field.
func (u *CurrencyProductUpsertBulk) AddDailyPurchaseLimit(v int) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddDailyPurchaseLimit(v)
	})
}

// UpdateDailyPurchaseLimit sets the "daily_purchase_limit" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateDailyPurchaseLimit() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateDailyPurchaseLimit()
	})
}

// SetTotalPurchaseLimit sets the "total_purchase_limit" field.
func (u *CurrencyProductUpsertBulk) SetTotalPurchaseLimit(v int) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetTotalPurchaseLimit(v)
	})
}

// AddTotalPurchaseLimit adds v to the "total_purchase_limit" field.
func (u *CurrencyProductUpsertBulk) AddTotalPurchaseLimit(v int) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.AddTotalPurchaseLimit(v)
	})
}

// UpdateTotalPurchaseLimit sets the "total_purchase_limit" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateTotalPurchaseLimit() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateTotalPurchaseLimit()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CurrencyProductUpsertBulk) SetUpdatedAt(v time.Time) *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CurrencyProductUpsertBulk) UpdateUpdatedAt() *CurrencyProductUpsertBulk {
	return u.Update(func(s *CurrencyProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CurrencyProductUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CurrencyProductCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CurrencyProductCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CurrencyProductUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
