// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/dailycheckin"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/temporarycreditgrant"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DailyCheckinUpdate is the builder for updating DailyCheckin entities.
type DailyCheckinUpdate struct {
	config
	hooks    []Hook
	mutation *DailyCheckinMutation
}

// Where appends a list predicates to the DailyCheckinUpdate builder.
func (_u *DailyCheckinUpdate) Where(ps ...predicate.DailyCheckin) *DailyCheckinUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DailyCheckinUpdate) SetUpdatedAt(v time.Time) *DailyCheckinUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyCheckinUpdate) SetUserID(v int64) *DailyCheckinUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyCheckinUpdate) SetNillableUserID(v *int64) *DailyCheckinUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *DailyCheckinUpdate) SetCheckinDate(v time.Time) *DailyCheckinUpdate {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *DailyCheckinUpdate) SetNillableCheckinDate(v *time.Time) *DailyCheckinUpdate {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetStreakDay sets the "streak_day" field.
func (_u *DailyCheckinUpdate) SetStreakDay(v int) *DailyCheckinUpdate {
	_u.mutation.ResetStreakDay()
	_u.mutation.SetStreakDay(v)
	return _u
}

// SetNillableStreakDay sets the "streak_day" field if the given value is not nil.
func (_u *DailyCheckinUpdate) SetNillableStreakDay(v *int) *DailyCheckinUpdate {
	if v != nil {
		_u.SetStreakDay(*v)
	}
	return _u
}

// AddStreakDay adds value to the "streak_day" field.
func (_u *DailyCheckinUpdate) AddStreakDay(v int) *DailyCheckinUpdate {
	_u.mutation.AddStreakDay(v)
	return _u
}

// SetRewardDay sets the "reward_day" field.
func (_u *DailyCheckinUpdate) SetRewardDay(v int) *DailyCheckinUpdate {
	_u.mutation.ResetRewardDay()
	_u.mutation.SetRewardDay(v)
	return _u
}

// SetNillableRewardDay sets the "reward_day" field if the given value is not nil.
func (_u *DailyCheckinUpdate) SetNillableRewardDay(v *int) *DailyCheckinUpdate {
	if v != nil {
		_u.SetRewardDay(*v)
	}
	return _u
}

// AddRewardDay adds value to the "reward_day" field.
func (_u *DailyCheckinUpdate) AddRewardDay(v int) *DailyCheckinUpdate {
	_u.mutation.AddRewardDay(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *DailyCheckinUpdate) SetRewardAmount(v float64) *DailyCheckinUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *DailyCheckinUpdate) SetNillableRewardAmount(v *float64) *DailyCheckinUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *DailyCheckinUpdate) AddRewardAmount(v float64) *DailyCheckinUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DailyCheckinUpdate) SetUser(v *User) *DailyCheckinUpdate {
	return _u.SetUserID(v.ID)
}

// SetTemporaryCreditGrantID sets the "temporary_credit_grant" edge to the TemporaryCreditGrant entity by ID.
func (_u *DailyCheckinUpdate) SetTemporaryCreditGrantID(id int64) *DailyCheckinUpdate {
	_u.mutation.SetTemporaryCreditGrantID(id)
	return _u
}

// SetNillableTemporaryCreditGrantID sets the "temporary_credit_grant" edge to the TemporaryCreditGrant entity by ID if the given value is not nil.
func (_u *DailyCheckinUpdate) SetNillableTemporaryCreditGrantID(id *int64) *DailyCheckinUpdate {
	if id != nil {
		_u = _u.SetTemporaryCreditGrantID(*id)
	}
	return _u
}

// SetTemporaryCreditGrant sets the "temporary_credit_grant" edge to the TemporaryCreditGrant entity.
func (_u *DailyCheckinUpdate) SetTemporaryCreditGrant(v *TemporaryCreditGrant) *DailyCheckinUpdate {
	return _u.SetTemporaryCreditGrantID(v.ID)
}

// Mutation returns the DailyCheckinMutation object of the builder.
func (_u *DailyCheckinUpdate) Mutation() *DailyCheckinMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DailyCheckinUpdate) ClearUser() *DailyCheckinUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTemporaryCreditGrant clears the "temporary_credit_grant" edge to the TemporaryCreditGrant entity.
func (_u *DailyCheckinUpdate) ClearTemporaryCreditGrant() *DailyCheckinUpdate {
	_u.mutation.ClearTemporaryCreditGrant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyCheckinUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyCheckinUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyCheckinUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyCheckinUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyCheckinUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dailycheckin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyCheckinUpdate) check() error {
	if v, ok := _u.mutation.StreakDay(); ok {
		if err := dailycheckin.StreakDayValidator(v); err != nil {
			return &ValidationError{Name: "streak_day", err: fmt.Errorf(`ent: validator failed for field "DailyCheckin.streak_day": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RewardDay(); ok {
		if err := dailycheckin.RewardDayValidator(v); err != nil {
			return &ValidationError{Name: "reward_day", err: fmt.Errorf(`ent: validator failed for field "DailyCheckin.reward_day": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DailyCheckin.user"`)
	}
	return nil
}

func (_u *DailyCheckinUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailycheckin.Table, dailycheckin.Columns, sqlgraph.NewFieldSpec(dailycheckin.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dailycheckin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(dailycheckin.FieldCheckinDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StreakDay(); ok {
		_spec.SetField(dailycheckin.FieldStreakDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDay(); ok {
		_spec.AddField(dailycheckin.FieldStreakDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardDay(); ok {
		_spec.SetField(dailycheckin.FieldRewardDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRewardDay(); ok {
		_spec.AddField(dailycheckin.FieldRewardDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(dailycheckin.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(dailycheckin.FieldRewardAmount, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckin.UserTable,
			Columns: []string{dailycheckin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckin.UserTable,
			Columns: []string{dailycheckin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TemporaryCreditGrantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   dailycheckin.TemporaryCreditGrantTable,
			Columns: []string{dailycheckin.TemporaryCreditGrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporarycreditgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemporaryCreditGrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   dailycheckin.TemporaryCreditGrantTable,
			Columns: []string{dailycheckin.TemporaryCreditGrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporarycreditgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailycheckin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyCheckinUpdateOne is the builder for updating a single DailyCheckin entity.
type DailyCheckinUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyCheckinMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DailyCheckinUpdateOne) SetUpdatedAt(v time.Time) *DailyCheckinUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyCheckinUpdateOne) SetUserID(v int64) *DailyCheckinUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyCheckinUpdateOne) SetNillableUserID(v *int64) *DailyCheckinUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *DailyCheckinUpdateOne) SetCheckinDate(v time.Time) *DailyCheckinUpdateOne {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *DailyCheckinUpdateOne) SetNillableCheckinDate(v *time.Time) *DailyCheckinUpdateOne {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetStreakDay sets the "streak_day" field.
func (_u *DailyCheckinUpdateOne) SetStreakDay(v int) *DailyCheckinUpdateOne {
	_u.mutation.ResetStreakDay()
	_u.mutation.SetStreakDay(v)
	return _u
}

// SetNillableStreakDay sets the "streak_day" field if the given value is not nil.
func (_u *DailyCheckinUpdateOne) SetNillableStreakDay(v *int) *DailyCheckinUpdateOne {
	if v != nil {
		_u.SetStreakDay(*v)
	}
	return _u
}

// AddStreakDay adds value to the "streak_day" field.
func (_u *DailyCheckinUpdateOne) AddStreakDay(v int) *DailyCheckinUpdateOne {
	_u.mutation.AddStreakDay(v)
	return _u
}

// SetRewardDay sets the "reward_day" field.
func (_u *DailyCheckinUpdateOne) SetRewardDay(v int) *DailyCheckinUpdateOne {
	_u.mutation.ResetRewardDay()
	_u.mutation.SetRewardDay(v)
	return _u
}

// SetNillableRewardDay sets the "reward_day" field if the given value is not nil.
func (_u *DailyCheckinUpdateOne) SetNillableRewardDay(v *int) *DailyCheckinUpdateOne {
	if v != nil {
		_u.SetRewardDay(*v)
	}
	return _u
}

// AddRewardDay adds value to the "reward_day" field.
func (_u *DailyCheckinUpdateOne) AddRewardDay(v int) *DailyCheckinUpdateOne {
	_u.mutation.AddRewardDay(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *DailyCheckinUpdateOne) SetRewardAmount(v float64) *DailyCheckinUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *DailyCheckinUpdateOne) SetNillableRewardAmount(v *float64) *DailyCheckinUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *DailyCheckinUpdateOne) AddRewardAmount(v float64) *DailyCheckinUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DailyCheckinUpdateOne) SetUser(v *User) *DailyCheckinUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetTemporaryCreditGrantID sets the "temporary_credit_grant" edge to the TemporaryCreditGrant entity by ID.
func (_u *DailyCheckinUpdateOne) SetTemporaryCreditGrantID(id int64) *DailyCheckinUpdateOne {
	_u.mutation.SetTemporaryCreditGrantID(id)
	return _u
}

// SetNillableTemporaryCreditGrantID sets the "temporary_credit_grant" edge to the TemporaryCreditGrant entity by ID if the given value is not nil.
func (_u *DailyCheckinUpdateOne) SetNillableTemporaryCreditGrantID(id *int64) *DailyCheckinUpdateOne {
	if id != nil {
		_u = _u.SetTemporaryCreditGrantID(*id)
	}
	return _u
}

// SetTemporaryCreditGrant sets the "temporary_credit_grant" edge to the TemporaryCreditGrant entity.
func (_u *DailyCheckinUpdateOne) SetTemporaryCreditGrant(v *TemporaryCreditGrant) *DailyCheckinUpdateOne {
	return _u.SetTemporaryCreditGrantID(v.ID)
}

// Mutation returns the DailyCheckinMutation object of the builder.
func (_u *DailyCheckinUpdateOne) Mutation() *DailyCheckinMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DailyCheckinUpdateOne) ClearUser() *DailyCheckinUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTemporaryCreditGrant clears the "temporary_credit_grant" edge to the TemporaryCreditGrant entity.
func (_u *DailyCheckinUpdateOne) ClearTemporaryCreditGrant() *DailyCheckinUpdateOne {
	_u.mutation.ClearTemporaryCreditGrant()
	return _u
}

// Where appends a list predicates to the DailyCheckinUpdate builder.
func (_u *DailyCheckinUpdateOne) Where(ps ...predicate.DailyCheckin) *DailyCheckinUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyCheckinUpdateOne) Select(field string, fields ...string) *DailyCheckinUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyCheckin entity.
func (_u *DailyCheckinUpdateOne) Save(ctx context.Context) (*DailyCheckin, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyCheckinUpdateOne) SaveX(ctx context.Context) *DailyCheckin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyCheckinUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyCheckinUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyCheckinUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dailycheckin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyCheckinUpdateOne) check() error {
	if v, ok := _u.mutation.StreakDay(); ok {
		if err := dailycheckin.StreakDayValidator(v); err != nil {
			return &ValidationError{Name: "streak_day", err: fmt.Errorf(`ent: validator failed for field "DailyCheckin.streak_day": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RewardDay(); ok {
		if err := dailycheckin.RewardDayValidator(v); err != nil {
			return &ValidationError{Name: "reward_day", err: fmt.Errorf(`ent: validator failed for field "DailyCheckin.reward_day": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DailyCheckin.user"`)
	}
	return nil
}

func (_u *DailyCheckinUpdateOne) sqlSave(ctx context.Context) (_node *DailyCheckin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailycheckin.Table, dailycheckin.Columns, sqlgraph.NewFieldSpec(dailycheckin.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyCheckin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailycheckin.FieldID)
		for _, f := range fields {
			if !dailycheckin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailycheckin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dailycheckin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(dailycheckin.FieldCheckinDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StreakDay(); ok {
		_spec.SetField(dailycheckin.FieldStreakDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDay(); ok {
		_spec.AddField(dailycheckin.FieldStreakDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardDay(); ok {
		_spec.SetField(dailycheckin.FieldRewardDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRewardDay(); ok {
		_spec.AddField(dailycheckin.FieldRewardDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(dailycheckin.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(dailycheckin.FieldRewardAmount, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckin.UserTable,
			Columns: []string{dailycheckin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckin.UserTable,
			Columns: []string{dailycheckin.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TemporaryCreditGrantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   dailycheckin.TemporaryCreditGrantTable,
			Columns: []string{dailycheckin.TemporaryCreditGrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporarycreditgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemporaryCreditGrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   dailycheckin.TemporaryCreditGrantTable,
			Columns: []string{dailycheckin.TemporaryCreditGrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporarycreditgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DailyCheckin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailycheckin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
