// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/malldailycreditsubscription"
)

// MallDailyCreditSubscriptionCreate is the builder for creating a MallDailyCreditSubscription entity.
type MallDailyCreditSubscriptionCreate struct {
	config
	mutation *MallDailyCreditSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *MallDailyCreditSubscriptionCreate) SetUserID(v int64) *MallDailyCreditSubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *MallDailyCreditSubscriptionCreate) SetPlanID(v int64) *MallDailyCreditSubscriptionCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *MallDailyCreditSubscriptionCreate) SetStartsAt(v time.Time) *MallDailyCreditSubscriptionCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetLastGrantDate sets the "last_grant_date" field.
func (_c *MallDailyCreditSubscriptionCreate) SetLastGrantDate(v time.Time) *MallDailyCreditSubscriptionCreate {
	_c.mutation.SetLastGrantDate(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *MallDailyCreditSubscriptionCreate) SetExpiresAt(v time.Time) *MallDailyCreditSubscriptionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MallDailyCreditSubscriptionCreate) SetStatus(v string) *MallDailyCreditSubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MallDailyCreditSubscriptionCreate) SetNillableStatus(v *string) *MallDailyCreditSubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MallDailyCreditSubscriptionCreate) SetCreatedAt(v time.Time) *MallDailyCreditSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MallDailyCreditSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *MallDailyCreditSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MallDailyCreditSubscriptionCreate) SetUpdatedAt(v time.Time) *MallDailyCreditSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MallDailyCreditSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *MallDailyCreditSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the MallDailyCreditSubscriptionMutation object of the builder.
func (_c *MallDailyCreditSubscriptionCreate) Mutation() *MallDailyCreditSubscriptionMutation {
	return _c.mutation
}

// Save creates the MallDailyCreditSubscription in the database.
func (_c *MallDailyCreditSubscriptionCreate) Save(ctx context.Context) (*MallDailyCreditSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MallDailyCreditSubscriptionCreate) SaveX(ctx context.Context) *MallDailyCreditSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MallDailyCreditSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MallDailyCreditSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MallDailyCreditSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := malldailycreditsubscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := malldailycreditsubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := malldailycreditsubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MallDailyCreditSubscriptionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MallDailyCreditSubscription.user_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "MallDailyCreditSubscription.plan_id"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "MallDailyCreditSubscription.starts_at"`)}
	}
	if _, ok := _c.mutation.LastGrantDate(); !ok {
		return &ValidationError{Name: "last_grant_date", err: errors.New(`ent: missing required field "MallDailyCreditSubscription.last_grant_date"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "MallDailyCreditSubscription.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MallDailyCreditSubscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := malldailycreditsubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MallDailyCreditSubscription.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MallDailyCreditSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MallDailyCreditSubscription.updated_at"`)}
	}
	return nil
}

func (_c *MallDailyCreditSubscriptionCreate) sqlSave(ctx context.Context) (*MallDailyCreditSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MallDailyCreditSubscriptionCreate) createSpec() (*MallDailyCreditSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &MallDailyCreditSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(malldailycreditsubscription.Table, sqlgraph.NewFieldSpec(malldailycreditsubscription.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(malldailycreditsubscription.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(malldailycreditsubscription.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(malldailycreditsubscription.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.LastGrantDate(); ok {
		_spec.SetField(malldailycreditsubscription.FieldLastGrantDate, field.TypeTime, value)
		_node.LastGrantDate = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(malldailycreditsubscription.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(malldailycreditsubscription.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(malldailycreditsubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(malldailycreditsubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MallDailyCreditSubscription.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MallDailyCreditSubscriptionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *MallDailyCreditSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *MallDailyCreditSubscriptionUpsertOne {
	_c.conflict = opts
	return &MallDailyCreditSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MallDailyCreditSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MallDailyCreditSubscriptionCreate) OnConflictColumns(columns ...string) *MallDailyCreditSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MallDailyCreditSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// MallDailyCreditSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one MallDailyCreditSubscription node.
	MallDailyCreditSubscriptionUpsertOne struct {
		create *MallDailyCreditSubscriptionCreate
	}

	// MallDailyCreditSubscriptionUpsert is the "OnConflict" setter.
	MallDailyCreditSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *MallDailyCreditSubscriptionUpsert) SetUserID(v int64) *MallDailyCreditSubscriptionUpsert {
	u.Set(malldailycreditsubscription.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsert) UpdateUserID() *MallDailyCreditSubscriptionUpsert {
	u.SetExcluded(malldailycreditsubscription.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *MallDailyCreditSubscriptionUpsert) AddUserID(v int64) *MallDailyCreditSubscriptionUpsert {
	u.Add(malldailycreditsubscription.FieldUserID, v)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *MallDailyCreditSubscriptionUpsert) SetPlanID(v int64) *MallDailyCreditSubscriptionUpsert {
	u.Set(malldailycreditsubscription.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsert) UpdatePlanID() *MallDailyCreditSubscriptionUpsert {
	u.SetExcluded(malldailycreditsubscription.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *MallDailyCreditSubscriptionUpsert) AddPlanID(v int64) *MallDailyCreditSubscriptionUpsert {
	u.Add(malldailycreditsubscription.FieldPlanID, v)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *MallDailyCreditSubscriptionUpsert) SetStartsAt(v time.Time) *MallDailyCreditSubscriptionUpsert {
	u.Set(malldailycreditsubscription.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsert) UpdateStartsAt() *MallDailyCreditSubscriptionUpsert {
	u.SetExcluded(malldailycreditsubscription.FieldStartsAt)
	return u
}

// SetLastGrantDate sets the "last_grant_date" field.
func (u *MallDailyCreditSubscriptionUpsert) SetLastGrantDate(v time.Time) *MallDailyCreditSubscriptionUpsert {
	u.Set(malldailycreditsubscription.FieldLastGrantDate, v)
	return u
}

// UpdateLastGrantDate sets the "last_grant_date" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsert) UpdateLastGrantDate() *MallDailyCreditSubscriptionUpsert {
	u.SetExcluded(malldailycreditsubscription.FieldLastGrantDate)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *MallDailyCreditSubscriptionUpsert) SetExpiresAt(v time.Time) *MallDailyCreditSubscriptionUpsert {
	u.Set(malldailycreditsubscription.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsert) UpdateExpiresAt() *MallDailyCreditSubscriptionUpsert {
	u.SetExcluded(malldailycreditsubscription.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *MallDailyCreditSubscriptionUpsert) SetStatus(v string) *MallDailyCreditSubscriptionUpsert {
	u.Set(malldailycreditsubscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsert) UpdateStatus() *MallDailyCreditSubscriptionUpsert {
	u.SetExcluded(malldailycreditsubscription.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MallDailyCreditSubscriptionUpsert) SetUpdatedAt(v time.Time) *MallDailyCreditSubscriptionUpsert {
	u.Set(malldailycreditsubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsert) UpdateUpdatedAt() *MallDailyCreditSubscriptionUpsert {
	u.SetExcluded(malldailycreditsubscription.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MallDailyCreditSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MallDailyCreditSubscriptionUpsertOne) UpdateNewValues() *MallDailyCreditSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(malldailycreditsubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MallDailyCreditSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MallDailyCreditSubscriptionUpsertOne) Ignore() *MallDailyCreditSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MallDailyCreditSubscriptionUpsertOne) DoNothing() *MallDailyCreditSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MallDailyCreditSubscriptionCreate.OnConflict
// documentation for more info.
func (u *MallDailyCreditSubscriptionUpsertOne) Update(set func(*MallDailyCreditSubscriptionUpsert)) *MallDailyCreditSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MallDailyCreditSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *MallDailyCreditSubscriptionUpsertOne) SetUserID(v int64) *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *MallDailyCreditSubscriptionUpsertOne) AddUserID(v int64) *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertOne) UpdateUserID() *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *MallDailyCreditSubscriptionUpsertOne) SetPlanID(v int64) *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *MallDailyCreditSubscriptionUpsertOne) AddPlanID(v int64) *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertOne) UpdatePlanID() *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *MallDailyCreditSubscriptionUpsertOne) SetStartsAt(v time.Time) *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertOne) UpdateStartsAt() *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetLastGrantDate sets the "last_grant_date" field.
func (u *MallDailyCreditSubscriptionUpsertOne) SetLastGrantDate(v time.Time) *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetLastGrantDate(v)
	})
}

// UpdateLastGrantDate sets the "last_grant_date" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertOne) UpdateLastGrantDate() *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateLastGrantDate()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *MallDailyCreditSubscriptionUpsertOne) SetExpiresAt(v time.Time) *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertOne) UpdateExpiresAt() *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *MallDailyCreditSubscriptionUpsertOne) SetStatus(v string) *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertOne) UpdateStatus() *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MallDailyCreditSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertOne) UpdateUpdatedAt() *MallDailyCreditSubscriptionUpsertOne {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MallDailyCreditSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MallDailyCreditSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MallDailyCreditSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MallDailyCreditSubscriptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MallDailyCreditSubscriptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MallDailyCreditSubscriptionCreateBulk is the builder for creating many MallDailyCreditSubscription entities in bulk.
type MallDailyCreditSubscriptionCreateBulk struct {
	config
	err      error
	builders []*MallDailyCreditSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the MallDailyCreditSubscription entities in the database.
func (_c *MallDailyCreditSubscriptionCreateBulk) Save(ctx context.Context) ([]*MallDailyCreditSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MallDailyCreditSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MallDailyCreditSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MallDailyCreditSubscriptionCreateBulk) SaveX(ctx context.Context) []*MallDailyCreditSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MallDailyCreditSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MallDailyCreditSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MallDailyCreditSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MallDailyCreditSubscriptionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *MallDailyCreditSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *MallDailyCreditSubscriptionUpsertBulk {
	_c.conflict = opts
	return &MallDailyCreditSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MallDailyCreditSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MallDailyCreditSubscriptionCreateBulk) OnConflictColumns(columns ...string) *MallDailyCreditSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MallDailyCreditSubscriptionUpsertBulk{
		create: _c,
	}
}

// MallDailyCreditSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of MallDailyCreditSubscription nodes.
type MallDailyCreditSubscriptionUpsertBulk struct {
	create *MallDailyCreditSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MallDailyCreditSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MallDailyCreditSubscriptionUpsertBulk) UpdateNewValues() *MallDailyCreditSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(malldailycreditsubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MallDailyCreditSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MallDailyCreditSubscriptionUpsertBulk) Ignore() *MallDailyCreditSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MallDailyCreditSubscriptionUpsertBulk) DoNothing() *MallDailyCreditSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MallDailyCreditSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *MallDailyCreditSubscriptionUpsertBulk) Update(set func(*MallDailyCreditSubscriptionUpsert)) *MallDailyCreditSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MallDailyCreditSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *MallDailyCreditSubscriptionUpsertBulk) SetUserID(v int64) *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *MallDailyCreditSubscriptionUpsertBulk) AddUserID(v int64) *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertBulk) UpdateUserID() *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *MallDailyCreditSubscriptionUpsertBulk) SetPlanID(v int64) *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *MallDailyCreditSubscriptionUpsertBulk) AddPlanID(v int64) *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertBulk) UpdatePlanID() *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *MallDailyCreditSubscriptionUpsertBulk) SetStartsAt(v time.Time) *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertBulk) UpdateStartsAt() *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetLastGrantDate sets the "last_grant_date" field.
func (u *MallDailyCreditSubscriptionUpsertBulk) SetLastGrantDate(v time.Time) *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetLastGrantDate(v)
	})
}

// UpdateLastGrantDate sets the "last_grant_date" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertBulk) UpdateLastGrantDate() *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateLastGrantDate()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *MallDailyCreditSubscriptionUpsertBulk) SetExpiresAt(v time.Time) *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertBulk) UpdateExpiresAt() *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *MallDailyCreditSubscriptionUpsertBulk) SetStatus(v string) *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertBulk) UpdateStatus() *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MallDailyCreditSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MallDailyCreditSubscriptionUpsertBulk) UpdateUpdatedAt() *MallDailyCreditSubscriptionUpsertBulk {
	return u.Update(func(s *MallDailyCreditSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MallDailyCreditSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MallDailyCreditSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MallDailyCreditSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MallDailyCreditSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
