// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentpurchasecounter"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentPurchaseCounterUpdate is the builder for updating PaymentPurchaseCounter entities.
type PaymentPurchaseCounterUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentPurchaseCounterMutation
}

// Where appends a list predicates to the PaymentPurchaseCounterUpdate builder.
func (_u *PaymentPurchaseCounterUpdate) Where(ps ...predicate.PaymentPurchaseCounter) *PaymentPurchaseCounterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentPurchaseCounterUpdate) SetUserID(v int64) *PaymentPurchaseCounterUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdate) SetNillableUserID(v *int64) *PaymentPurchaseCounterUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *PaymentPurchaseCounterUpdate) AddUserID(v int64) *PaymentPurchaseCounterUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetProductType sets the "product_type" field.
func (_u *PaymentPurchaseCounterUpdate) SetProductType(v string) *PaymentPurchaseCounterUpdate {
	_u.mutation.SetProductType(v)
	return _u
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdate) SetNillableProductType(v *string) *PaymentPurchaseCounterUpdate {
	if v != nil {
		_u.SetProductType(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *PaymentPurchaseCounterUpdate) SetProductID(v int64) *PaymentPurchaseCounterUpdate {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdate) SetNillableProductID(v *int64) *PaymentPurchaseCounterUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *PaymentPurchaseCounterUpdate) AddProductID(v int64) *PaymentPurchaseCounterUpdate {
	_u.mutation.AddProductID(v)
	return _u
}

// SetPeriodType sets the "period_type" field.
func (_u *PaymentPurchaseCounterUpdate) SetPeriodType(v string) *PaymentPurchaseCounterUpdate {
	_u.mutation.SetPeriodType(v)
	return _u
}

// SetNillablePeriodType sets the "period_type" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdate) SetNillablePeriodType(v *string) *PaymentPurchaseCounterUpdate {
	if v != nil {
		_u.SetPeriodType(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *PaymentPurchaseCounterUpdate) SetPeriodStart(v time.Time) *PaymentPurchaseCounterUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdate) SetNillablePeriodStart(v *time.Time) *PaymentPurchaseCounterUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetReservedCount sets the "reserved_count" field.
func (_u *PaymentPurchaseCounterUpdate) SetReservedCount(v int) *PaymentPurchaseCounterUpdate {
	_u.mutation.ResetReservedCount()
	_u.mutation.SetReservedCount(v)
	return _u
}

// SetNillableReservedCount sets the "reserved_count" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdate) SetNillableReservedCount(v *int) *PaymentPurchaseCounterUpdate {
	if v != nil {
		_u.SetReservedCount(*v)
	}
	return _u
}

// AddReservedCount adds value to the "reserved_count" field.
func (_u *PaymentPurchaseCounterUpdate) AddReservedCount(v int) *PaymentPurchaseCounterUpdate {
	_u.mutation.AddReservedCount(v)
	return _u
}

// SetConsumedCount sets the "consumed_count" field.
func (_u *PaymentPurchaseCounterUpdate) SetConsumedCount(v int) *PaymentPurchaseCounterUpdate {
	_u.mutation.ResetConsumedCount()
	_u.mutation.SetConsumedCount(v)
	return _u
}

// SetNillableConsumedCount sets the "consumed_count" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdate) SetNillableConsumedCount(v *int) *PaymentPurchaseCounterUpdate {
	if v != nil {
		_u.SetConsumedCount(*v)
	}
	return _u
}

// AddConsumedCount adds value to the "consumed_count" field.
func (_u *PaymentPurchaseCounterUpdate) AddConsumedCount(v int) *PaymentPurchaseCounterUpdate {
	_u.mutation.AddConsumedCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentPurchaseCounterUpdate) SetUpdatedAt(v time.Time) *PaymentPurchaseCounterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentPurchaseCounterMutation object of the builder.
func (_u *PaymentPurchaseCounterUpdate) Mutation() *PaymentPurchaseCounterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentPurchaseCounterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentPurchaseCounterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentPurchaseCounterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentPurchaseCounterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentPurchaseCounterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentpurchasecounter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentPurchaseCounterUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := paymentpurchasecounter.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductType(); ok {
		if err := paymentpurchasecounter.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.product_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductID(); ok {
		if err := paymentpurchasecounter.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.product_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeriodType(); ok {
		if err := paymentpurchasecounter.PeriodTypeValidator(v); err != nil {
			return &ValidationError{Name: "period_type", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.period_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReservedCount(); ok {
		if err := paymentpurchasecounter.ReservedCountValidator(v); err != nil {
			return &ValidationError{Name: "reserved_count", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.reserved_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConsumedCount(); ok {
		if err := paymentpurchasecounter.ConsumedCountValidator(v); err != nil {
			return &ValidationError{Name: "consumed_count", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.consumed_count": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentPurchaseCounterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentpurchasecounter.Table, paymentpurchasecounter.Columns, sqlgraph.NewFieldSpec(paymentpurchasecounter.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(paymentpurchasecounter.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(paymentpurchasecounter.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductType(); ok {
		_spec.SetField(paymentpurchasecounter.FieldProductType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(paymentpurchasecounter.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(paymentpurchasecounter.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PeriodType(); ok {
		_spec.SetField(paymentpurchasecounter.FieldPeriodType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(paymentpurchasecounter.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReservedCount(); ok {
		_spec.SetField(paymentpurchasecounter.FieldReservedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReservedCount(); ok {
		_spec.AddField(paymentpurchasecounter.FieldReservedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsumedCount(); ok {
		_spec.SetField(paymentpurchasecounter.FieldConsumedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsumedCount(); ok {
		_spec.AddField(paymentpurchasecounter.FieldConsumedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentpurchasecounter.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentpurchasecounter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentPurchaseCounterUpdateOne is the builder for updating a single PaymentPurchaseCounter entity.
type PaymentPurchaseCounterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentPurchaseCounterMutation
}

// SetUserID sets the "user_id" field.
func (_u *PaymentPurchaseCounterUpdateOne) SetUserID(v int64) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdateOne) SetNillableUserID(v *int64) *PaymentPurchaseCounterUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *PaymentPurchaseCounterUpdateOne) AddUserID(v int64) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetProductType sets the "product_type" field.
func (_u *PaymentPurchaseCounterUpdateOne) SetProductType(v string) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.SetProductType(v)
	return _u
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdateOne) SetNillableProductType(v *string) *PaymentPurchaseCounterUpdateOne {
	if v != nil {
		_u.SetProductType(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *PaymentPurchaseCounterUpdateOne) SetProductID(v int64) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdateOne) SetNillableProductID(v *int64) *PaymentPurchaseCounterUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *PaymentPurchaseCounterUpdateOne) AddProductID(v int64) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.AddProductID(v)
	return _u
}

// SetPeriodType sets the "period_type" field.
func (_u *PaymentPurchaseCounterUpdateOne) SetPeriodType(v string) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.SetPeriodType(v)
	return _u
}

// SetNillablePeriodType sets the "period_type" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdateOne) SetNillablePeriodType(v *string) *PaymentPurchaseCounterUpdateOne {
	if v != nil {
		_u.SetPeriodType(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *PaymentPurchaseCounterUpdateOne) SetPeriodStart(v time.Time) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdateOne) SetNillablePeriodStart(v *time.Time) *PaymentPurchaseCounterUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetReservedCount sets the "reserved_count" field.
func (_u *PaymentPurchaseCounterUpdateOne) SetReservedCount(v int) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.ResetReservedCount()
	_u.mutation.SetReservedCount(v)
	return _u
}

// SetNillableReservedCount sets the "reserved_count" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdateOne) SetNillableReservedCount(v *int) *PaymentPurchaseCounterUpdateOne {
	if v != nil {
		_u.SetReservedCount(*v)
	}
	return _u
}

// AddReservedCount adds value to the "reserved_count" field.
func (_u *PaymentPurchaseCounterUpdateOne) AddReservedCount(v int) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.AddReservedCount(v)
	return _u
}

// SetConsumedCount sets the "consumed_count" field.
func (_u *PaymentPurchaseCounterUpdateOne) SetConsumedCount(v int) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.ResetConsumedCount()
	_u.mutation.SetConsumedCount(v)
	return _u
}

// SetNillableConsumedCount sets the "consumed_count" field if the given value is not nil.
func (_u *PaymentPurchaseCounterUpdateOne) SetNillableConsumedCount(v *int) *PaymentPurchaseCounterUpdateOne {
	if v != nil {
		_u.SetConsumedCount(*v)
	}
	return _u
}

// AddConsumedCount adds value to the "consumed_count" field.
func (_u *PaymentPurchaseCounterUpdateOne) AddConsumedCount(v int) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.AddConsumedCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentPurchaseCounterUpdateOne) SetUpdatedAt(v time.Time) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentPurchaseCounterMutation object of the builder.
func (_u *PaymentPurchaseCounterUpdateOne) Mutation() *PaymentPurchaseCounterMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentPurchaseCounterUpdate builder.
func (_u *PaymentPurchaseCounterUpdateOne) Where(ps ...predicate.PaymentPurchaseCounter) *PaymentPurchaseCounterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentPurchaseCounterUpdateOne) Select(field string, fields ...string) *PaymentPurchaseCounterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentPurchaseCounter entity.
func (_u *PaymentPurchaseCounterUpdateOne) Save(ctx context.Context) (*PaymentPurchaseCounter, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentPurchaseCounterUpdateOne) SaveX(ctx context.Context) *PaymentPurchaseCounter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentPurchaseCounterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentPurchaseCounterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentPurchaseCounterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentpurchasecounter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentPurchaseCounterUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := paymentpurchasecounter.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductType(); ok {
		if err := paymentpurchasecounter.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.product_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductID(); ok {
		if err := paymentpurchasecounter.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.product_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeriodType(); ok {
		if err := paymentpurchasecounter.PeriodTypeValidator(v); err != nil {
			return &ValidationError{Name: "period_type", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.period_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReservedCount(); ok {
		if err := paymentpurchasecounter.ReservedCountValidator(v); err != nil {
			return &ValidationError{Name: "reserved_count", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.reserved_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConsumedCount(); ok {
		if err := paymentpurchasecounter.ConsumedCountValidator(v); err != nil {
			return &ValidationError{Name: "consumed_count", err: fmt.Errorf(`ent: validator failed for field "PaymentPurchaseCounter.consumed_count": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentPurchaseCounterUpdateOne) sqlSave(ctx context.Context) (_node *PaymentPurchaseCounter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentpurchasecounter.Table, paymentpurchasecounter.Columns, sqlgraph.NewFieldSpec(paymentpurchasecounter.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentPurchaseCounter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentpurchasecounter.FieldID)
		for _, f := range fields {
			if !paymentpurchasecounter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentpurchasecounter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(paymentpurchasecounter.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(paymentpurchasecounter.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductType(); ok {
		_spec.SetField(paymentpurchasecounter.FieldProductType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(paymentpurchasecounter.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(paymentpurchasecounter.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PeriodType(); ok {
		_spec.SetField(paymentpurchasecounter.FieldPeriodType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(paymentpurchasecounter.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReservedCount(); ok {
		_spec.SetField(paymentpurchasecounter.FieldReservedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReservedCount(); ok {
		_spec.AddField(paymentpurchasecounter.FieldReservedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConsumedCount(); ok {
		_spec.SetField(paymentpurchasecounter.FieldConsumedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsumedCount(); ok {
		_spec.AddField(paymentpurchasecounter.FieldConsumedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentpurchasecounter.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentPurchaseCounter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentpurchasecounter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
