// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentpurchasecounter"
)

// PaymentPurchaseCounter is the model entity for the PaymentPurchaseCounter schema.
type PaymentPurchaseCounter struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ProductType holds the value of the "product_type" field.
	ProductType string `json:"product_type,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID int64 `json:"product_id,omitempty"`
	// PeriodType holds the value of the "period_type" field.
	PeriodType string `json:"period_type,omitempty"`
	// PeriodStart holds the value of the "period_start" field.
	PeriodStart time.Time `json:"period_start,omitempty"`
	// ReservedCount holds the value of the "reserved_count" field.
	ReservedCount int `json:"reserved_count,omitempty"`
	// ConsumedCount holds the value of the "consumed_count" field.
	ConsumedCount int `json:"consumed_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentPurchaseCounter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentpurchasecounter.FieldID, paymentpurchasecounter.FieldUserID, paymentpurchasecounter.FieldProductID, paymentpurchasecounter.FieldReservedCount, paymentpurchasecounter.FieldConsumedCount:
			values[i] = new(sql.NullInt64)
		case paymentpurchasecounter.FieldProductType, paymentpurchasecounter.FieldPeriodType:
			values[i] = new(sql.NullString)
		case paymentpurchasecounter.FieldPeriodStart, paymentpurchasecounter.FieldCreatedAt, paymentpurchasecounter.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentPurchaseCounter fields.
func (_m *PaymentPurchaseCounter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentpurchasecounter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentpurchasecounter.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case paymentpurchasecounter.FieldProductType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_type", values[i])
			} else if value.Valid {
				_m.ProductType = value.String
			}
		case paymentpurchasecounter.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = value.Int64
			}
		case paymentpurchasecounter.FieldPeriodType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field period_type", values[i])
			} else if value.Valid {
				_m.PeriodType = value.String
			}
		case paymentpurchasecounter.FieldPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_start", values[i])
			} else if value.Valid {
				_m.PeriodStart = value.Time
			}
		case paymentpurchasecounter.FieldReservedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_count", values[i])
			} else if value.Valid {
				_m.ReservedCount = int(value.Int64)
			}
		case paymentpurchasecounter.FieldConsumedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_count", values[i])
			} else if value.Valid {
				_m.ConsumedCount = int(value.Int64)
			}
		case paymentpurchasecounter.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentpurchasecounter.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentPurchaseCounter.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentPurchaseCounter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentPurchaseCounter.
// Note that you need to call PaymentPurchaseCounter.Unwrap() before calling this method if this PaymentPurchaseCounter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentPurchaseCounter) Update() *PaymentPurchaseCounterUpdateOne {
	return NewPaymentPurchaseCounterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentPurchaseCounter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentPurchaseCounter) Unwrap() *PaymentPurchaseCounter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentPurchaseCounter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentPurchaseCounter) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentPurchaseCounter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("product_type=")
	builder.WriteString(_m.ProductType)
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	builder.WriteString("period_type=")
	builder.WriteString(_m.PeriodType)
	builder.WriteString(", ")
	builder.WriteString("period_start=")
	builder.WriteString(_m.PeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reserved_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservedCount))
	builder.WriteString(", ")
	builder.WriteString("consumed_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsumedCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentPurchaseCounters is a parsable slice of PaymentPurchaseCounter.
type PaymentPurchaseCounters []*PaymentPurchaseCounter
