// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentpurchaselimitevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentPurchaseLimitEventDelete is the builder for deleting a PaymentPurchaseLimitEvent entity.
type PaymentPurchaseLimitEventDelete struct {
	config
	hooks    []Hook
	mutation *PaymentPurchaseLimitEventMutation
}

// Where appends a list predicates to the PaymentPurchaseLimitEventDelete builder.
func (_d *PaymentPurchaseLimitEventDelete) Where(ps ...predicate.PaymentPurchaseLimitEvent) *PaymentPurchaseLimitEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PaymentPurchaseLimitEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentPurchaseLimitEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PaymentPurchaseLimitEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentpurchaselimitevent.Table, sqlgraph.NewFieldSpec(paymentpurchaselimitevent.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PaymentPurchaseLimitEventDeleteOne is the builder for deleting a single PaymentPurchaseLimitEvent entity.
type PaymentPurchaseLimitEventDeleteOne struct {
	_d *PaymentPurchaseLimitEventDelete
}

// Where appends a list predicates to the PaymentPurchaseLimitEventDelete builder.
func (_d *PaymentPurchaseLimitEventDeleteOne) Where(ps ...predicate.PaymentPurchaseLimitEvent) *PaymentPurchaseLimitEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PaymentPurchaseLimitEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentpurchaselimitevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentPurchaseLimitEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
