// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/temporarycreditconsumption"
	"github.com/Wei-Shaw/sub2api/ent/temporarycreditgrant"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// TemporaryCreditConsumption is the model entity for the TemporaryCreditConsumption schema.
type TemporaryCreditConsumption struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GrantID holds the value of the "grant_id" field.
	GrantID int64 `json:"grant_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TemporaryCreditConsumptionQuery when eager-loading is set.
	Edges        TemporaryCreditConsumptionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TemporaryCreditConsumptionEdges holds the relations/edges for other nodes in the graph.
type TemporaryCreditConsumptionEdges struct {
	// Grant holds the value of the grant edge.
	Grant *TemporaryCreditGrant `json:"grant,omitempty"`
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GrantOrErr returns the Grant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TemporaryCreditConsumptionEdges) GrantOrErr() (*TemporaryCreditGrant, error) {
	if e.Grant != nil {
		return e.Grant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: temporarycreditgrant.Label}
	}
	return nil, &NotLoadedError{edge: "grant"}
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TemporaryCreditConsumptionEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TemporaryCreditConsumption) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case temporarycreditconsumption.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case temporarycreditconsumption.FieldID, temporarycreditconsumption.FieldGrantID, temporarycreditconsumption.FieldUsageLogID:
			values[i] = new(sql.NullInt64)
		case temporarycreditconsumption.FieldRequestID:
			values[i] = new(sql.NullString)
		case temporarycreditconsumption.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TemporaryCreditConsumption fields.
func (_m *TemporaryCreditConsumption) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case temporarycreditconsumption.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case temporarycreditconsumption.FieldGrantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_id", values[i])
			} else if value.Valid {
				_m.GrantID = value.Int64
			}
		case temporarycreditconsumption.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case temporarycreditconsumption.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case temporarycreditconsumption.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case temporarycreditconsumption.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TemporaryCreditConsumption.
// This includes values selected through modifiers, order, etc.
func (_m *TemporaryCreditConsumption) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGrant queries the "grant" edge of the TemporaryCreditConsumption entity.
func (_m *TemporaryCreditConsumption) QueryGrant() *TemporaryCreditGrantQuery {
	return NewTemporaryCreditConsumptionClient(_m.config).QueryGrant(_m)
}

// QueryUsageLog queries the "usage_log" edge of the TemporaryCreditConsumption entity.
func (_m *TemporaryCreditConsumption) QueryUsageLog() *UsageLogQuery {
	return NewTemporaryCreditConsumptionClient(_m.config).QueryUsageLog(_m)
}

// Update returns a builder for updating this TemporaryCreditConsumption.
// Note that you need to call TemporaryCreditConsumption.Unwrap() before calling this method if this TemporaryCreditConsumption
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TemporaryCreditConsumption) Update() *TemporaryCreditConsumptionUpdateOne {
	return NewTemporaryCreditConsumptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TemporaryCreditConsumption entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TemporaryCreditConsumption) Unwrap() *TemporaryCreditConsumption {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TemporaryCreditConsumption is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TemporaryCreditConsumption) String() string {
	var builder strings.Builder
	builder.WriteString("TemporaryCreditConsumption(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("grant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrantID))
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TemporaryCreditConsumptions is a parsable slice of TemporaryCreditConsumption.
type TemporaryCreditConsumptions []*TemporaryCreditConsumption
