// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/temporarycreditconsumption"
	"github.com/Wei-Shaw/sub2api/ent/temporarycreditgrant"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// TemporaryCreditConsumptionUpdate is the builder for updating TemporaryCreditConsumption entities.
type TemporaryCreditConsumptionUpdate struct {
	config
	hooks    []Hook
	mutation *TemporaryCreditConsumptionMutation
}

// Where appends a list predicates to the TemporaryCreditConsumptionUpdate builder.
func (_u *TemporaryCreditConsumptionUpdate) Where(ps ...predicate.TemporaryCreditConsumption) *TemporaryCreditConsumptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGrantID sets the "grant_id" field.
func (_u *TemporaryCreditConsumptionUpdate) SetGrantID(v int64) *TemporaryCreditConsumptionUpdate {
	_u.mutation.SetGrantID(v)
	return _u
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_u *TemporaryCreditConsumptionUpdate) SetNillableGrantID(v *int64) *TemporaryCreditConsumptionUpdate {
	if v != nil {
		_u.SetGrantID(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *TemporaryCreditConsumptionUpdate) SetUsageLogID(v int64) *TemporaryCreditConsumptionUpdate {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *TemporaryCreditConsumptionUpdate) SetNillableUsageLogID(v *int64) *TemporaryCreditConsumptionUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *TemporaryCreditConsumptionUpdate) ClearUsageLogID() *TemporaryCreditConsumptionUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TemporaryCreditConsumptionUpdate) SetAmount(v float64) *TemporaryCreditConsumptionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TemporaryCreditConsumptionUpdate) SetNillableAmount(v *float64) *TemporaryCreditConsumptionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TemporaryCreditConsumptionUpdate) AddAmount(v float64) *TemporaryCreditConsumptionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetGrant sets the "grant" edge to the TemporaryCreditGrant entity.
func (_u *TemporaryCreditConsumptionUpdate) SetGrant(v *TemporaryCreditGrant) *TemporaryCreditConsumptionUpdate {
	return _u.SetGrantID(v.ID)
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *TemporaryCreditConsumptionUpdate) SetUsageLog(v *UsageLog) *TemporaryCreditConsumptionUpdate {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the TemporaryCreditConsumptionMutation object of the builder.
func (_u *TemporaryCreditConsumptionUpdate) Mutation() *TemporaryCreditConsumptionMutation {
	return _u.mutation
}

// ClearGrant clears the "grant" edge to the TemporaryCreditGrant entity.
func (_u *TemporaryCreditConsumptionUpdate) ClearGrant() *TemporaryCreditConsumptionUpdate {
	_u.mutation.ClearGrant()
	return _u
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *TemporaryCreditConsumptionUpdate) ClearUsageLog() *TemporaryCreditConsumptionUpdate {
	_u.mutation.ClearUsageLog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TemporaryCreditConsumptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemporaryCreditConsumptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TemporaryCreditConsumptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemporaryCreditConsumptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemporaryCreditConsumptionUpdate) check() error {
	if _u.mutation.GrantCleared() && len(_u.mutation.GrantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TemporaryCreditConsumption.grant"`)
	}
	return nil
}

func (_u *TemporaryCreditConsumptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(temporarycreditconsumption.Table, temporarycreditconsumption.Columns, sqlgraph.NewFieldSpec(temporarycreditconsumption.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(temporarycreditconsumption.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(temporarycreditconsumption.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(temporarycreditconsumption.FieldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.GrantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.GrantTable,
			Columns: []string{temporarycreditconsumption.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporarycreditgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.GrantTable,
			Columns: []string{temporarycreditconsumption.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporarycreditgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.UsageLogTable,
			Columns: []string{temporarycreditconsumption.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.UsageLogTable,
			Columns: []string{temporarycreditconsumption.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{temporarycreditconsumption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TemporaryCreditConsumptionUpdateOne is the builder for updating a single TemporaryCreditConsumption entity.
type TemporaryCreditConsumptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TemporaryCreditConsumptionMutation
}

// SetGrantID sets the "grant_id" field.
func (_u *TemporaryCreditConsumptionUpdateOne) SetGrantID(v int64) *TemporaryCreditConsumptionUpdateOne {
	_u.mutation.SetGrantID(v)
	return _u
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_u *TemporaryCreditConsumptionUpdateOne) SetNillableGrantID(v *int64) *TemporaryCreditConsumptionUpdateOne {
	if v != nil {
		_u.SetGrantID(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *TemporaryCreditConsumptionUpdateOne) SetUsageLogID(v int64) *TemporaryCreditConsumptionUpdateOne {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *TemporaryCreditConsumptionUpdateOne) SetNillableUsageLogID(v *int64) *TemporaryCreditConsumptionUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *TemporaryCreditConsumptionUpdateOne) ClearUsageLogID() *TemporaryCreditConsumptionUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TemporaryCreditConsumptionUpdateOne) SetAmount(v float64) *TemporaryCreditConsumptionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TemporaryCreditConsumptionUpdateOne) SetNillableAmount(v *float64) *TemporaryCreditConsumptionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TemporaryCreditConsumptionUpdateOne) AddAmount(v float64) *TemporaryCreditConsumptionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetGrant sets the "grant" edge to the TemporaryCreditGrant entity.
func (_u *TemporaryCreditConsumptionUpdateOne) SetGrant(v *TemporaryCreditGrant) *TemporaryCreditConsumptionUpdateOne {
	return _u.SetGrantID(v.ID)
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *TemporaryCreditConsumptionUpdateOne) SetUsageLog(v *UsageLog) *TemporaryCreditConsumptionUpdateOne {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the TemporaryCreditConsumptionMutation object of the builder.
func (_u *TemporaryCreditConsumptionUpdateOne) Mutation() *TemporaryCreditConsumptionMutation {
	return _u.mutation
}

// ClearGrant clears the "grant" edge to the TemporaryCreditGrant entity.
func (_u *TemporaryCreditConsumptionUpdateOne) ClearGrant() *TemporaryCreditConsumptionUpdateOne {
	_u.mutation.ClearGrant()
	return _u
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *TemporaryCreditConsumptionUpdateOne) ClearUsageLog() *TemporaryCreditConsumptionUpdateOne {
	_u.mutation.ClearUsageLog()
	return _u
}

// Where appends a list predicates to the TemporaryCreditConsumptionUpdate builder.
func (_u *TemporaryCreditConsumptionUpdateOne) Where(ps ...predicate.TemporaryCreditConsumption) *TemporaryCreditConsumptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TemporaryCreditConsumptionUpdateOne) Select(field string, fields ...string) *TemporaryCreditConsumptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TemporaryCreditConsumption entity.
func (_u *TemporaryCreditConsumptionUpdateOne) Save(ctx context.Context) (*TemporaryCreditConsumption, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemporaryCreditConsumptionUpdateOne) SaveX(ctx context.Context) *TemporaryCreditConsumption {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TemporaryCreditConsumptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemporaryCreditConsumptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemporaryCreditConsumptionUpdateOne) check() error {
	if _u.mutation.GrantCleared() && len(_u.mutation.GrantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TemporaryCreditConsumption.grant"`)
	}
	return nil
}

func (_u *TemporaryCreditConsumptionUpdateOne) sqlSave(ctx context.Context) (_node *TemporaryCreditConsumption, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(temporarycreditconsumption.Table, temporarycreditconsumption.Columns, sqlgraph.NewFieldSpec(temporarycreditconsumption.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TemporaryCreditConsumption.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, temporarycreditconsumption.FieldID)
		for _, f := range fields {
			if !temporarycreditconsumption.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != temporarycreditconsumption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(temporarycreditconsumption.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(temporarycreditconsumption.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(temporarycreditconsumption.FieldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.GrantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.GrantTable,
			Columns: []string{temporarycreditconsumption.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporarycreditgrant.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.GrantTable,
			Columns: []string{temporarycreditconsumption.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporarycreditgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.UsageLogTable,
			Columns: []string{temporarycreditconsumption.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.UsageLogTable,
			Columns: []string{temporarycreditconsumption.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TemporaryCreditConsumption{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{temporarycreditconsumption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
