// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/temporarycreditconsumption"
	"github.com/Wei-Shaw/sub2api/ent/temporarycreditgrant"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// TemporaryCreditConsumptionCreate is the builder for creating a TemporaryCreditConsumption entity.
type TemporaryCreditConsumptionCreate struct {
	config
	mutation *TemporaryCreditConsumptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGrantID sets the "grant_id" field.
func (_c *TemporaryCreditConsumptionCreate) SetGrantID(v int64) *TemporaryCreditConsumptionCreate {
	_c.mutation.SetGrantID(v)
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *TemporaryCreditConsumptionCreate) SetUsageLogID(v int64) *TemporaryCreditConsumptionCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *TemporaryCreditConsumptionCreate) SetNillableUsageLogID(v *int64) *TemporaryCreditConsumptionCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *TemporaryCreditConsumptionCreate) SetRequestID(v string) *TemporaryCreditConsumptionCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *TemporaryCreditConsumptionCreate) SetNillableRequestID(v *string) *TemporaryCreditConsumptionCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *TemporaryCreditConsumptionCreate) SetAmount(v float64) *TemporaryCreditConsumptionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TemporaryCreditConsumptionCreate) SetCreatedAt(v time.Time) *TemporaryCreditConsumptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TemporaryCreditConsumptionCreate) SetNillableCreatedAt(v *time.Time) *TemporaryCreditConsumptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetGrant sets the "grant" edge to the TemporaryCreditGrant entity.
func (_c *TemporaryCreditConsumptionCreate) SetGrant(v *TemporaryCreditGrant) *TemporaryCreditConsumptionCreate {
	return _c.SetGrantID(v.ID)
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_c *TemporaryCreditConsumptionCreate) SetUsageLog(v *UsageLog) *TemporaryCreditConsumptionCreate {
	return _c.SetUsageLogID(v.ID)
}

// Mutation returns the TemporaryCreditConsumptionMutation object of the builder.
func (_c *TemporaryCreditConsumptionCreate) Mutation() *TemporaryCreditConsumptionMutation {
	return _c.mutation
}

// Save creates the TemporaryCreditConsumption in the database.
func (_c *TemporaryCreditConsumptionCreate) Save(ctx context.Context) (*TemporaryCreditConsumption, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TemporaryCreditConsumptionCreate) SaveX(ctx context.Context) *TemporaryCreditConsumption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemporaryCreditConsumptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemporaryCreditConsumptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TemporaryCreditConsumptionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := temporarycreditconsumption.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TemporaryCreditConsumptionCreate) check() error {
	if _, ok := _c.mutation.GrantID(); !ok {
		return &ValidationError{Name: "grant_id", err: errors.New(`ent: missing required field "TemporaryCreditConsumption.grant_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := temporarycreditconsumption.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "TemporaryCreditConsumption.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "TemporaryCreditConsumption.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TemporaryCreditConsumption.created_at"`)}
	}
	if len(_c.mutation.GrantIDs()) == 0 {
		return &ValidationError{Name: "grant", err: errors.New(`ent: missing required edge "TemporaryCreditConsumption.grant"`)}
	}
	return nil
}

func (_c *TemporaryCreditConsumptionCreate) sqlSave(ctx context.Context) (*TemporaryCreditConsumption, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TemporaryCreditConsumptionCreate) createSpec() (*TemporaryCreditConsumption, *sqlgraph.CreateSpec) {
	var (
		_node = &TemporaryCreditConsumption{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(temporarycreditconsumption.Table, sqlgraph.NewFieldSpec(temporarycreditconsumption.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(temporarycreditconsumption.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(temporarycreditconsumption.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(temporarycreditconsumption.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.GrantTable,
			Columns: []string{temporarycreditconsumption.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporarycreditgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GrantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   temporarycreditconsumption.UsageLogTable,
			Columns: []string{temporarycreditconsumption.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsageLogID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TemporaryCreditConsumption.Create().
//		SetGrantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TemporaryCreditConsumptionUpsert) {
//			SetGrantID(v+v).
//		}).
//		Exec(ctx)
func (_c *TemporaryCreditConsumptionCreate) OnConflict(opts ...sql.ConflictOption) *TemporaryCreditConsumptionUpsertOne {
	_c.conflict = opts
	return &TemporaryCreditConsumptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TemporaryCreditConsumption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TemporaryCreditConsumptionCreate) OnConflictColumns(columns ...string) *TemporaryCreditConsumptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TemporaryCreditConsumptionUpsertOne{
		create: _c,
	}
}

type (
	// TemporaryCreditConsumptionUpsertOne is the builder for "upsert"-ing
	//  one TemporaryCreditConsumption node.
	TemporaryCreditConsumptionUpsertOne struct {
		create *TemporaryCreditConsumptionCreate
	}

	// TemporaryCreditConsumptionUpsert is the "OnConflict" setter.
	TemporaryCreditConsumptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetGrantID sets the "grant_id" field.
func (u *TemporaryCreditConsumptionUpsert) SetGrantID(v int64) *TemporaryCreditConsumptionUpsert {
	u.Set(temporarycreditconsumption.FieldGrantID, v)
	return u
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *TemporaryCreditConsumptionUpsert) UpdateGrantID() *TemporaryCreditConsumptionUpsert {
	u.SetExcluded(temporarycreditconsumption.FieldGrantID)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *TemporaryCreditConsumptionUpsert) SetUsageLogID(v int64) *TemporaryCreditConsumptionUpsert {
	u.Set(temporarycreditconsumption.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *TemporaryCreditConsumptionUpsert) UpdateUsageLogID() *TemporaryCreditConsumptionUpsert {
	u.SetExcluded(temporarycreditconsumption.FieldUsageLogID)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *TemporaryCreditConsumptionUpsert) ClearUsageLogID() *TemporaryCreditConsumptionUpsert {
	u.SetNull(temporarycreditconsumption.FieldUsageLogID)
	return u
}

// SetAmount sets the "amount" field.
func (u *TemporaryCreditConsumptionUpsert) SetAmount(v float64) *TemporaryCreditConsumptionUpsert {
	u.Set(temporarycreditconsumption.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TemporaryCreditConsumptionUpsert) UpdateAmount() *TemporaryCreditConsumptionUpsert {
	u.SetExcluded(temporarycreditconsumption.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *TemporaryCreditConsumptionUpsert) AddAmount(v float64) *TemporaryCreditConsumptionUpsert {
	u.Add(temporarycreditconsumption.FieldAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TemporaryCreditConsumption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TemporaryCreditConsumptionUpsertOne) UpdateNewValues() *TemporaryCreditConsumptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.RequestID(); exists {
			s.SetIgnore(temporarycreditconsumption.FieldRequestID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(temporarycreditconsumption.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TemporaryCreditConsumption.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TemporaryCreditConsumptionUpsertOne) Ignore() *TemporaryCreditConsumptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TemporaryCreditConsumptionUpsertOne) DoNothing() *TemporaryCreditConsumptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TemporaryCreditConsumptionCreate.OnConflict
// documentation for more info.
func (u *TemporaryCreditConsumptionUpsertOne) Update(set func(*TemporaryCreditConsumptionUpsert)) *TemporaryCreditConsumptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TemporaryCreditConsumptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *TemporaryCreditConsumptionUpsertOne) SetGrantID(v int64) *TemporaryCreditConsumptionUpsertOne {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *TemporaryCreditConsumptionUpsertOne) UpdateGrantID() *TemporaryCreditConsumptionUpsertOne {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.UpdateGrantID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *TemporaryCreditConsumptionUpsertOne) SetUsageLogID(v int64) *TemporaryCreditConsumptionUpsertOne {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *TemporaryCreditConsumptionUpsertOne) UpdateUsageLogID() *TemporaryCreditConsumptionUpsertOne {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *TemporaryCreditConsumptionUpsertOne) ClearUsageLogID() *TemporaryCreditConsumptionUpsertOne {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.ClearUsageLogID()
	})
}

// SetAmount sets the "amount" field.
func (u *TemporaryCreditConsumptionUpsertOne) SetAmount(v float64) *TemporaryCreditConsumptionUpsertOne {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TemporaryCreditConsumptionUpsertOne) AddAmount(v float64) *TemporaryCreditConsumptionUpsertOne {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TemporaryCreditConsumptionUpsertOne) UpdateAmount() *TemporaryCreditConsumptionUpsertOne {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *TemporaryCreditConsumptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TemporaryCreditConsumptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TemporaryCreditConsumptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TemporaryCreditConsumptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TemporaryCreditConsumptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TemporaryCreditConsumptionCreateBulk is the builder for creating many TemporaryCreditConsumption entities in bulk.
type TemporaryCreditConsumptionCreateBulk struct {
	config
	err      error
	builders []*TemporaryCreditConsumptionCreate
	conflict []sql.ConflictOption
}

// Save creates the TemporaryCreditConsumption entities in the database.
func (_c *TemporaryCreditConsumptionCreateBulk) Save(ctx context.Context) ([]*TemporaryCreditConsumption, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TemporaryCreditConsumption, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TemporaryCreditConsumptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TemporaryCreditConsumptionCreateBulk) SaveX(ctx context.Context) []*TemporaryCreditConsumption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemporaryCreditConsumptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemporaryCreditConsumptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TemporaryCreditConsumption.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TemporaryCreditConsumptionUpsert) {
//			SetGrantID(v+v).
//		}).
//		Exec(ctx)
func (_c *TemporaryCreditConsumptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *TemporaryCreditConsumptionUpsertBulk {
	_c.conflict = opts
	return &TemporaryCreditConsumptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TemporaryCreditConsumption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TemporaryCreditConsumptionCreateBulk) OnConflictColumns(columns ...string) *TemporaryCreditConsumptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TemporaryCreditConsumptionUpsertBulk{
		create: _c,
	}
}

// TemporaryCreditConsumptionUpsertBulk is the builder for "upsert"-ing
// a bulk of TemporaryCreditConsumption nodes.
type TemporaryCreditConsumptionUpsertBulk struct {
	create *TemporaryCreditConsumptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TemporaryCreditConsumption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TemporaryCreditConsumptionUpsertBulk) UpdateNewValues() *TemporaryCreditConsumptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.RequestID(); exists {
				s.SetIgnore(temporarycreditconsumption.FieldRequestID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(temporarycreditconsumption.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TemporaryCreditConsumption.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TemporaryCreditConsumptionUpsertBulk) Ignore() *TemporaryCreditConsumptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TemporaryCreditConsumptionUpsertBulk) DoNothing() *TemporaryCreditConsumptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TemporaryCreditConsumptionCreateBulk.OnConflict
// documentation for more info.
func (u *TemporaryCreditConsumptionUpsertBulk) Update(set func(*TemporaryCreditConsumptionUpsert)) *TemporaryCreditConsumptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TemporaryCreditConsumptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *TemporaryCreditConsumptionUpsertBulk) SetGrantID(v int64) *TemporaryCreditConsumptionUpsertBulk {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *TemporaryCreditConsumptionUpsertBulk) UpdateGrantID() *TemporaryCreditConsumptionUpsertBulk {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.UpdateGrantID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *TemporaryCreditConsumptionUpsertBulk) SetUsageLogID(v int64) *TemporaryCreditConsumptionUpsertBulk {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *TemporaryCreditConsumptionUpsertBulk) UpdateUsageLogID() *TemporaryCreditConsumptionUpsertBulk {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *TemporaryCreditConsumptionUpsertBulk) ClearUsageLogID() *TemporaryCreditConsumptionUpsertBulk {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.ClearUsageLogID()
	})
}

// SetAmount sets the "amount" field.
func (u *TemporaryCreditConsumptionUpsertBulk) SetAmount(v float64) *TemporaryCreditConsumptionUpsertBulk {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TemporaryCreditConsumptionUpsertBulk) AddAmount(v float64) *TemporaryCreditConsumptionUpsertBulk {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TemporaryCreditConsumptionUpsertBulk) UpdateAmount() *TemporaryCreditConsumptionUpsertBulk {
	return u.Update(func(s *TemporaryCreditConsumptionUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *TemporaryCreditConsumptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TemporaryCreditConsumptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TemporaryCreditConsumptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TemporaryCreditConsumptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
