// Code generated by ent, DO NOT EDIT.

package dailycheckin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dailycheckin type in the database.
	Label = "daily_checkin"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCheckinDate holds the string denoting the checkin_date field in the database.
	FieldCheckinDate = "checkin_date"
	// FieldStreakDay holds the string denoting the streak_day field in the database.
	FieldStreakDay = "streak_day"
	// FieldRewardDay holds the string denoting the reward_day field in the database.
	FieldRewardDay = "reward_day"
	// FieldRewardAmount holds the string denoting the reward_amount field in the database.
	FieldRewardAmount = "reward_amount"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeTemporaryCreditGrant holds the string denoting the temporary_credit_grant edge name in mutations.
	EdgeTemporaryCreditGrant = "temporary_credit_grant"
	// Table holds the table name of the dailycheckin in the database.
	Table = "daily_checkins"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "daily_checkins"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// TemporaryCreditGrantTable is the table that holds the temporary_credit_grant relation/edge.
	TemporaryCreditGrantTable = "temporary_credit_grants"
	// TemporaryCreditGrantInverseTable is the table name for the TemporaryCreditGrant entity.
	// It exists in this package in order to avoid circular dependency with the "temporarycreditgrant" package.
	TemporaryCreditGrantInverseTable = "temporary_credit_grants"
	// TemporaryCreditGrantColumn is the table column denoting the temporary_credit_grant relation/edge.
	TemporaryCreditGrantColumn = "checkin_id"
)

// Columns holds all SQL columns for dailycheckin fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldCheckinDate,
	FieldStreakDay,
	FieldRewardDay,
	FieldRewardAmount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// StreakDayValidator is a validator for the "streak_day" field. It is called by the builders before save.
	StreakDayValidator func(int) error
	// RewardDayValidator is a validator for the "reward_day" field. It is called by the builders before save.
	RewardDayValidator func(int) error
)

// OrderOption defines the ordering options for the DailyCheckin queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCheckinDate orders the results by the checkin_date field.
func ByCheckinDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckinDate, opts...).ToFunc()
}

// ByStreakDay orders the results by the streak_day field.
func ByStreakDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreakDay, opts...).ToFunc()
}

// ByRewardDay orders the results by the reward_day field.
func ByRewardDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardDay, opts...).ToFunc()
}

// ByRewardAmount orders the results by the reward_amount field.
func ByRewardAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardAmount, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByTemporaryCreditGrantField orders the results by temporary_credit_grant field.
func ByTemporaryCreditGrantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTemporaryCreditGrantStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newTemporaryCreditGrantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TemporaryCreditGrantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, TemporaryCreditGrantTable, TemporaryCreditGrantColumn),
	)
}
