// Code generated by ent, DO NOT EDIT.

package currencyproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldDescription, v))
}

// PaymentPrice applies equality check predicate on the "payment_price" field. It's identical to PaymentPriceEQ.
func PaymentPrice(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldPaymentPrice, v))
}

// PaymentCreditType applies equality check predicate on the "payment_credit_type" field. It's identical to PaymentCreditTypeEQ.
func PaymentCreditType(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldPaymentCreditType, v))
}

// CreditedType applies equality check predicate on the "credited_type" field. It's identical to CreditedTypeEQ.
func CreditedType(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldCreditedType, v))
}

// CreditedAmount applies equality check predicate on the "credited_amount" field. It's identical to CreditedAmountEQ.
func CreditedAmount(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldCreditedAmount, v))
}

// CreditedPermanentAmount applies equality check predicate on the "credited_permanent_amount" field. It's identical to CreditedPermanentAmountEQ.
func CreditedPermanentAmount(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldCreditedPermanentAmount, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldSortOrder, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldIsActive, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldForSale, v))
}

// DailyPurchaseLimit applies equality check predicate on the "daily_purchase_limit" field. It's identical to DailyPurchaseLimitEQ.
func DailyPurchaseLimit(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldDailyPurchaseLimit, v))
}

// TotalPurchaseLimit applies equality check predicate on the "total_purchase_limit" field. It's identical to TotalPurchaseLimitEQ.
func TotalPurchaseLimit(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldTotalPurchaseLimit, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldContainsFold(FieldDescription, v))
}

// PaymentPriceEQ applies the EQ predicate on the "payment_price" field.
func PaymentPriceEQ(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldPaymentPrice, v))
}

// PaymentPriceNEQ applies the NEQ predicate on the "payment_price" field.
func PaymentPriceNEQ(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldPaymentPrice, v))
}

// PaymentPriceIn applies the In predicate on the "payment_price" field.
func PaymentPriceIn(vs ...float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldPaymentPrice, vs...))
}

// PaymentPriceNotIn applies the NotIn predicate on the "payment_price" field.
func PaymentPriceNotIn(vs ...float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldPaymentPrice, vs...))
}

// PaymentPriceGT applies the GT predicate on the "payment_price" field.
func PaymentPriceGT(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldPaymentPrice, v))
}

// PaymentPriceGTE applies the GTE predicate on the "payment_price" field.
func PaymentPriceGTE(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldPaymentPrice, v))
}

// PaymentPriceLT applies the LT predicate on the "payment_price" field.
func PaymentPriceLT(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldPaymentPrice, v))
}

// PaymentPriceLTE applies the LTE predicate on the "payment_price" field.
func PaymentPriceLTE(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldPaymentPrice, v))
}

// PaymentCreditTypeEQ applies the EQ predicate on the "payment_credit_type" field.
func PaymentCreditTypeEQ(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldPaymentCreditType, v))
}

// PaymentCreditTypeNEQ applies the NEQ predicate on the "payment_credit_type" field.
func PaymentCreditTypeNEQ(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldPaymentCreditType, v))
}

// PaymentCreditTypeIn applies the In predicate on the "payment_credit_type" field.
func PaymentCreditTypeIn(vs ...string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldPaymentCreditType, vs...))
}

// PaymentCreditTypeNotIn applies the NotIn predicate on the "payment_credit_type" field.
func PaymentCreditTypeNotIn(vs ...string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldPaymentCreditType, vs...))
}

// PaymentCreditTypeGT applies the GT predicate on the "payment_credit_type" field.
func PaymentCreditTypeGT(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldPaymentCreditType, v))
}

// PaymentCreditTypeGTE applies the GTE predicate on the "payment_credit_type" field.
func PaymentCreditTypeGTE(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldPaymentCreditType, v))
}

// PaymentCreditTypeLT applies the LT predicate on the "payment_credit_type" field.
func PaymentCreditTypeLT(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldPaymentCreditType, v))
}

// PaymentCreditTypeLTE applies the LTE predicate on the "payment_credit_type" field.
func PaymentCreditTypeLTE(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldPaymentCreditType, v))
}

// PaymentCreditTypeContains applies the Contains predicate on the "payment_credit_type" field.
func PaymentCreditTypeContains(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldContains(FieldPaymentCreditType, v))
}

// PaymentCreditTypeHasPrefix applies the HasPrefix predicate on the "payment_credit_type" field.
func PaymentCreditTypeHasPrefix(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldHasPrefix(FieldPaymentCreditType, v))
}

// PaymentCreditTypeHasSuffix applies the HasSuffix predicate on the "payment_credit_type" field.
func PaymentCreditTypeHasSuffix(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldHasSuffix(FieldPaymentCreditType, v))
}

// PaymentCreditTypeEqualFold applies the EqualFold predicate on the "payment_credit_type" field.
func PaymentCreditTypeEqualFold(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEqualFold(FieldPaymentCreditType, v))
}

// PaymentCreditTypeContainsFold applies the ContainsFold predicate on the "payment_credit_type" field.
func PaymentCreditTypeContainsFold(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldContainsFold(FieldPaymentCreditType, v))
}

// CreditedTypeEQ applies the EQ predicate on the "credited_type" field.
func CreditedTypeEQ(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldCreditedType, v))
}

// CreditedTypeNEQ applies the NEQ predicate on the "credited_type" field.
func CreditedTypeNEQ(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldCreditedType, v))
}

// CreditedTypeIn applies the In predicate on the "credited_type" field.
func CreditedTypeIn(vs ...string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldCreditedType, vs...))
}

// CreditedTypeNotIn applies the NotIn predicate on the "credited_type" field.
func CreditedTypeNotIn(vs ...string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldCreditedType, vs...))
}

// CreditedTypeGT applies the GT predicate on the "credited_type" field.
func CreditedTypeGT(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldCreditedType, v))
}

// CreditedTypeGTE applies the GTE predicate on the "credited_type" field.
func CreditedTypeGTE(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldCreditedType, v))
}

// CreditedTypeLT applies the LT predicate on the "credited_type" field.
func CreditedTypeLT(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldCreditedType, v))
}

// CreditedTypeLTE applies the LTE predicate on the "credited_type" field.
func CreditedTypeLTE(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldCreditedType, v))
}

// CreditedTypeContains applies the Contains predicate on the "credited_type" field.
func CreditedTypeContains(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldContains(FieldCreditedType, v))
}

// CreditedTypeHasPrefix applies the HasPrefix predicate on the "credited_type" field.
func CreditedTypeHasPrefix(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldHasPrefix(FieldCreditedType, v))
}

// CreditedTypeHasSuffix applies the HasSuffix predicate on the "credited_type" field.
func CreditedTypeHasSuffix(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldHasSuffix(FieldCreditedType, v))
}

// CreditedTypeEqualFold applies the EqualFold predicate on the "credited_type" field.
func CreditedTypeEqualFold(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEqualFold(FieldCreditedType, v))
}

// CreditedTypeContainsFold applies the ContainsFold predicate on the "credited_type" field.
func CreditedTypeContainsFold(v string) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldContainsFold(FieldCreditedType, v))
}

// CreditedAmountEQ applies the EQ predicate on the "credited_amount" field.
func CreditedAmountEQ(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldCreditedAmount, v))
}

// CreditedAmountNEQ applies the NEQ predicate on the "credited_amount" field.
func CreditedAmountNEQ(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldCreditedAmount, v))
}

// CreditedAmountIn applies the In predicate on the "credited_amount" field.
func CreditedAmountIn(vs ...float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldCreditedAmount, vs...))
}

// CreditedAmountNotIn applies the NotIn predicate on the "credited_amount" field.
func CreditedAmountNotIn(vs ...float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldCreditedAmount, vs...))
}

// CreditedAmountGT applies the GT predicate on the "credited_amount" field.
func CreditedAmountGT(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldCreditedAmount, v))
}

// CreditedAmountGTE applies the GTE predicate on the "credited_amount" field.
func CreditedAmountGTE(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldCreditedAmount, v))
}

// CreditedAmountLT applies the LT predicate on the "credited_amount" field.
func CreditedAmountLT(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldCreditedAmount, v))
}

// CreditedAmountLTE applies the LTE predicate on the "credited_amount" field.
func CreditedAmountLTE(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldCreditedAmount, v))
}

// CreditedPermanentAmountEQ applies the EQ predicate on the "credited_permanent_amount" field.
func CreditedPermanentAmountEQ(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldCreditedPermanentAmount, v))
}

// CreditedPermanentAmountNEQ applies the NEQ predicate on the "credited_permanent_amount" field.
func CreditedPermanentAmountNEQ(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldCreditedPermanentAmount, v))
}

// CreditedPermanentAmountIn applies the In predicate on the "credited_permanent_amount" field.
func CreditedPermanentAmountIn(vs ...float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldCreditedPermanentAmount, vs...))
}

// CreditedPermanentAmountNotIn applies the NotIn predicate on the "credited_permanent_amount" field.
func CreditedPermanentAmountNotIn(vs ...float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldCreditedPermanentAmount, vs...))
}

// CreditedPermanentAmountGT applies the GT predicate on the "credited_permanent_amount" field.
func CreditedPermanentAmountGT(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldCreditedPermanentAmount, v))
}

// CreditedPermanentAmountGTE applies the GTE predicate on the "credited_permanent_amount" field.
func CreditedPermanentAmountGTE(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldCreditedPermanentAmount, v))
}

// CreditedPermanentAmountLT applies the LT predicate on the "credited_permanent_amount" field.
func CreditedPermanentAmountLT(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldCreditedPermanentAmount, v))
}

// CreditedPermanentAmountLTE applies the LTE predicate on the "credited_permanent_amount" field.
func CreditedPermanentAmountLTE(v float64) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldCreditedPermanentAmount, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldSortOrder, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldIsActive, v))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldForSale, v))
}

// DailyPurchaseLimitEQ applies the EQ predicate on the "daily_purchase_limit" field.
func DailyPurchaseLimitEQ(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldDailyPurchaseLimit, v))
}

// DailyPurchaseLimitNEQ applies the NEQ predicate on the "daily_purchase_limit" field.
func DailyPurchaseLimitNEQ(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldDailyPurchaseLimit, v))
}

// DailyPurchaseLimitIn applies the In predicate on the "daily_purchase_limit" field.
func DailyPurchaseLimitIn(vs ...int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldDailyPurchaseLimit, vs...))
}

// DailyPurchaseLimitNotIn applies the NotIn predicate on the "daily_purchase_limit" field.
func DailyPurchaseLimitNotIn(vs ...int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldDailyPurchaseLimit, vs...))
}

// DailyPurchaseLimitGT applies the GT predicate on the "daily_purchase_limit" field.
func DailyPurchaseLimitGT(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldDailyPurchaseLimit, v))
}

// DailyPurchaseLimitGTE applies the GTE predicate on the "daily_purchase_limit" field.
func DailyPurchaseLimitGTE(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldDailyPurchaseLimit, v))
}

// DailyPurchaseLimitLT applies the LT predicate on the "daily_purchase_limit" field.
func DailyPurchaseLimitLT(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldDailyPurchaseLimit, v))
}

// DailyPurchaseLimitLTE applies the LTE predicate on the "daily_purchase_limit" field.
func DailyPurchaseLimitLTE(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldDailyPurchaseLimit, v))
}

// TotalPurchaseLimitEQ applies the EQ predicate on the "total_purchase_limit" field.
func TotalPurchaseLimitEQ(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldTotalPurchaseLimit, v))
}

// TotalPurchaseLimitNEQ applies the NEQ predicate on the "total_purchase_limit" field.
func TotalPurchaseLimitNEQ(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldTotalPurchaseLimit, v))
}

// TotalPurchaseLimitIn applies the In predicate on the "total_purchase_limit" field.
func TotalPurchaseLimitIn(vs ...int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldTotalPurchaseLimit, vs...))
}

// TotalPurchaseLimitNotIn applies the NotIn predicate on the "total_purchase_limit" field.
func TotalPurchaseLimitNotIn(vs ...int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldTotalPurchaseLimit, vs...))
}

// TotalPurchaseLimitGT applies the GT predicate on the "total_purchase_limit" field.
func TotalPurchaseLimitGT(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldTotalPurchaseLimit, v))
}

// TotalPurchaseLimitGTE applies the GTE predicate on the "total_purchase_limit" field.
func TotalPurchaseLimitGTE(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldTotalPurchaseLimit, v))
}

// TotalPurchaseLimitLT applies the LT predicate on the "total_purchase_limit" field.
func TotalPurchaseLimitLT(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldTotalPurchaseLimit, v))
}

// TotalPurchaseLimitLTE applies the LTE predicate on the "total_purchase_limit" field.
func TotalPurchaseLimitLTE(v int) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldTotalPurchaseLimit, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CurrencyProduct) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CurrencyProduct) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CurrencyProduct) predicate.CurrencyProduct {
	return predicate.CurrencyProduct(sql.NotPredicates(p))
}
