// Code generated by ent, DO NOT EDIT.

package batchimagecredithold

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the batchimagecredithold type in the database.
	Label = "batch_image_credit_hold"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBatchID holds the string denoting the batch_id field in the database.
	FieldBatchID = "batch_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldHoldAmount holds the string denoting the hold_amount field in the database.
	FieldHoldAmount = "hold_amount"
	// FieldTemporaryReservedAmount holds the string denoting the temporary_reserved_amount field in the database.
	FieldTemporaryReservedAmount = "temporary_reserved_amount"
	// FieldPermanentReservedAmount holds the string denoting the permanent_reserved_amount field in the database.
	FieldPermanentReservedAmount = "permanent_reserved_amount"
	// FieldCapturedAmount holds the string denoting the captured_amount field in the database.
	FieldCapturedAmount = "captured_amount"
	// FieldTemporaryCapturedAmount holds the string denoting the temporary_captured_amount field in the database.
	FieldTemporaryCapturedAmount = "temporary_captured_amount"
	// FieldPermanentCapturedAmount holds the string denoting the permanent_captured_amount field in the database.
	FieldPermanentCapturedAmount = "permanent_captured_amount"
	// FieldExpiredUnrestoredAmount holds the string denoting the expired_unrestored_amount field in the database.
	FieldExpiredUnrestoredAmount = "expired_unrestored_amount"
	// FieldReserveFingerprint holds the string denoting the reserve_fingerprint field in the database.
	FieldReserveFingerprint = "reserve_fingerprint"
	// FieldTerminalFingerprint holds the string denoting the terminal_fingerprint field in the database.
	FieldTerminalFingerprint = "terminal_fingerprint"
	// FieldReservedAt holds the string denoting the reserved_at field in the database.
	FieldReservedAt = "reserved_at"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeAllocations holds the string denoting the allocations edge name in mutations.
	EdgeAllocations = "allocations"
	// Table holds the table name of the batchimagecredithold in the database.
	Table = "batch_image_credit_holds"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "batch_image_credit_holds"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "batch_image_credit_holds"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "batch_image_credit_holds"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// AllocationsTable is the table that holds the allocations relation/edge.
	AllocationsTable = "batch_image_credit_hold_allocations"
	// AllocationsInverseTable is the table name for the BatchImageCreditHoldAllocation entity.
	// It exists in this package in order to avoid circular dependency with the "batchimagecreditholdallocation" package.
	AllocationsInverseTable = "batch_image_credit_hold_allocations"
	// AllocationsColumn is the table column denoting the allocations relation/edge.
	AllocationsColumn = "hold_id"
)

// Columns holds all SQL columns for batchimagecredithold fields.
var Columns = []string{
	FieldID,
	FieldBatchID,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldStatus,
	FieldHoldAmount,
	FieldTemporaryReservedAmount,
	FieldPermanentReservedAmount,
	FieldCapturedAmount,
	FieldTemporaryCapturedAmount,
	FieldPermanentCapturedAmount,
	FieldExpiredUnrestoredAmount,
	FieldReserveFingerprint,
	FieldTerminalFingerprint,
	FieldReservedAt,
	FieldSettledAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BatchIDValidator is a validator for the "batch_id" field. It is called by the builders before save.
	BatchIDValidator func(string) error
	// DefaultTemporaryReservedAmount holds the default value on creation for the "temporary_reserved_amount" field.
	DefaultTemporaryReservedAmount float64
	// DefaultPermanentReservedAmount holds the default value on creation for the "permanent_reserved_amount" field.
	DefaultPermanentReservedAmount float64
	// DefaultCapturedAmount holds the default value on creation for the "captured_amount" field.
	DefaultCapturedAmount float64
	// DefaultTemporaryCapturedAmount holds the default value on creation for the "temporary_captured_amount" field.
	DefaultTemporaryCapturedAmount float64
	// DefaultPermanentCapturedAmount holds the default value on creation for the "permanent_captured_amount" field.
	DefaultPermanentCapturedAmount float64
	// DefaultExpiredUnrestoredAmount holds the default value on creation for the "expired_unrestored_amount" field.
	DefaultExpiredUnrestoredAmount float64
	// ReserveFingerprintValidator is a validator for the "reserve_fingerprint" field. It is called by the builders before save.
	ReserveFingerprintValidator func(string) error
	// TerminalFingerprintValidator is a validator for the "terminal_fingerprint" field. It is called by the builders before save.
	TerminalFingerprintValidator func(string) error
	// DefaultReservedAt holds the default value on creation for the "reserved_at" field.
	DefaultReservedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusReserved is the default value of the Status enum.
const DefaultStatus = StatusReserved

// Status values.
const (
	StatusReserved Status = "reserved"
	StatusCaptured Status = "captured"
	StatusReleased Status = "released"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusReserved, StatusCaptured, StatusReleased:
		return nil
	default:
		return fmt.Errorf("batchimagecredithold: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the BatchImageCreditHold queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBatchID orders the results by the batch_id field.
func ByBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByHoldAmount orders the results by the hold_amount field.
func ByHoldAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoldAmount, opts...).ToFunc()
}

// ByTemporaryReservedAmount orders the results by the temporary_reserved_amount field.
func ByTemporaryReservedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemporaryReservedAmount, opts...).ToFunc()
}

// ByPermanentReservedAmount orders the results by the permanent_reserved_amount field.
func ByPermanentReservedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermanentReservedAmount, opts...).ToFunc()
}

// ByCapturedAmount orders the results by the captured_amount field.
func ByCapturedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAmount, opts...).ToFunc()
}

// ByTemporaryCapturedAmount orders the results by the temporary_captured_amount field.
func ByTemporaryCapturedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemporaryCapturedAmount, opts...).ToFunc()
}

// ByPermanentCapturedAmount orders the results by the permanent_captured_amount field.
func ByPermanentCapturedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermanentCapturedAmount, opts...).ToFunc()
}

// ByExpiredUnrestoredAmount orders the results by the expired_unrestored_amount field.
func ByExpiredUnrestoredAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiredUnrestoredAmount, opts...).ToFunc()
}

// ByReserveFingerprint orders the results by the reserve_fingerprint field.
func ByReserveFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReserveFingerprint, opts...).ToFunc()
}

// ByTerminalFingerprint orders the results by the terminal_fingerprint field.
func ByTerminalFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTerminalFingerprint, opts...).ToFunc()
}

// ByReservedAt orders the results by the reserved_at field.
func ByReservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedAt, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByAllocationsCount orders the results by allocations count.
func ByAllocationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAllocationsStep(), opts...)
	}
}

// ByAllocations orders the results by allocations terms.
func ByAllocations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAllocationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newAllocationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AllocationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AllocationsTable, AllocationsColumn),
	)
}
