// Code generated by ent, DO NOT EDIT.

package paymentrefundattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentrefundattempt type in the database.
	Label = "payment_refund_attempt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAttemptID holds the string denoting the attempt_id field in the database.
	FieldAttemptID = "attempt_id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldRefundAmount holds the string denoting the refund_amount field in the database.
	FieldRefundAmount = "refund_amount"
	// FieldGatewayAmount holds the string denoting the gateway_amount field in the database.
	FieldGatewayAmount = "gateway_amount"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldOriginalOrderStatus holds the string denoting the original_order_status field in the database.
	FieldOriginalOrderStatus = "original_order_status"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldDeductBalance holds the string denoting the deduct_balance field in the database.
	FieldDeductBalance = "deduct_balance"
	// FieldForce holds the string denoting the force field in the database.
	FieldForce = "force"
	// FieldDeductionType holds the string denoting the deduction_type field in the database.
	FieldDeductionType = "deduction_type"
	// FieldHeldBalanceAmount holds the string denoting the held_balance_amount field in the database.
	FieldHeldBalanceAmount = "held_balance_amount"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldSubscriptionDays holds the string denoting the subscription_days field in the database.
	FieldSubscriptionDays = "subscription_days"
	// FieldSubscriptionOriginalExpiresAt holds the string denoting the subscription_original_expires_at field in the database.
	FieldSubscriptionOriginalExpiresAt = "subscription_original_expires_at"
	// FieldSubscriptionOriginalStatus holds the string denoting the subscription_original_status field in the database.
	FieldSubscriptionOriginalStatus = "subscription_original_status"
	// FieldSubscriptionRevoked holds the string denoting the subscription_revoked field in the database.
	FieldSubscriptionRevoked = "subscription_revoked"
	// FieldDeductionState holds the string denoting the deduction_state field in the database.
	FieldDeductionState = "deduction_state"
	// FieldProviderRefundID holds the string denoting the provider_refund_id field in the database.
	FieldProviderRefundID = "provider_refund_id"
	// FieldProviderState holds the string denoting the provider_state field in the database.
	FieldProviderState = "provider_state"
	// FieldProviderResult holds the string denoting the provider_result field in the database.
	FieldProviderResult = "provider_result"
	// FieldManualReview holds the string denoting the manual_review field in the database.
	FieldManualReview = "manual_review"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentrefundattempt in the database.
	Table = "payment_refund_attempts"
)

// Columns holds all SQL columns for paymentrefundattempt fields.
var Columns = []string{
	FieldID,
	FieldAttemptID,
	FieldOrderID,
	FieldRefundAmount,
	FieldGatewayAmount,
	FieldReason,
	FieldOriginalOrderStatus,
	FieldSource,
	FieldDeductBalance,
	FieldForce,
	FieldDeductionType,
	FieldHeldBalanceAmount,
	FieldSubscriptionID,
	FieldSubscriptionDays,
	FieldSubscriptionOriginalExpiresAt,
	FieldSubscriptionOriginalStatus,
	FieldSubscriptionRevoked,
	FieldDeductionState,
	FieldProviderRefundID,
	FieldProviderState,
	FieldProviderResult,
	FieldManualReview,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AttemptIDValidator is a validator for the "attempt_id" field. It is called by the builders before save.
	AttemptIDValidator func(string) error
	// OrderIDValidator is a validator for the "order_id" field. It is called by the builders before save.
	OrderIDValidator func(int64) error
	// DefaultReason holds the default value on creation for the "reason" field.
	DefaultReason string
	// OriginalOrderStatusValidator is a validator for the "original_order_status" field. It is called by the builders before save.
	OriginalOrderStatusValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultDeductionType holds the default value on creation for the "deduction_type" field.
	DefaultDeductionType string
	// DeductionTypeValidator is a validator for the "deduction_type" field. It is called by the builders before save.
	DeductionTypeValidator func(string) error
	// DefaultHeldBalanceAmount holds the default value on creation for the "held_balance_amount" field.
	DefaultHeldBalanceAmount float64
	// DefaultSubscriptionDays holds the default value on creation for the "subscription_days" field.
	DefaultSubscriptionDays int
	// SubscriptionOriginalStatusValidator is a validator for the "subscription_original_status" field. It is called by the builders before save.
	SubscriptionOriginalStatusValidator func(string) error
	// DefaultSubscriptionRevoked holds the default value on creation for the "subscription_revoked" field.
	DefaultSubscriptionRevoked bool
	// DefaultDeductionState holds the default value on creation for the "deduction_state" field.
	DefaultDeductionState string
	// DeductionStateValidator is a validator for the "deduction_state" field. It is called by the builders before save.
	DeductionStateValidator func(string) error
	// ProviderRefundIDValidator is a validator for the "provider_refund_id" field. It is called by the builders before save.
	ProviderRefundIDValidator func(string) error
	// DefaultProviderState holds the default value on creation for the "provider_state" field.
	DefaultProviderState string
	// ProviderStateValidator is a validator for the "provider_state" field. It is called by the builders before save.
	ProviderStateValidator func(string) error
	// DefaultProviderResult holds the default value on creation for the "provider_result" field.
	DefaultProviderResult string
	// DefaultManualReview holds the default value on creation for the "manual_review" field.
	DefaultManualReview bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentRefundAttempt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAttemptID orders the results by the attempt_id field.
func ByAttemptID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByRefundAmount orders the results by the refund_amount field.
func ByRefundAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundAmount, opts...).ToFunc()
}

// ByGatewayAmount orders the results by the gateway_amount field.
func ByGatewayAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayAmount, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByOriginalOrderStatus orders the results by the original_order_status field.
func ByOriginalOrderStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalOrderStatus, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByDeductBalance orders the results by the deduct_balance field.
func ByDeductBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeductBalance, opts...).ToFunc()
}

// ByForce orders the results by the force field.
func ByForce(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForce, opts...).ToFunc()
}

// ByDeductionType orders the results by the deduction_type field.
func ByDeductionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeductionType, opts...).ToFunc()
}

// ByHeldBalanceAmount orders the results by the held_balance_amount field.
func ByHeldBalanceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeldBalanceAmount, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// BySubscriptionDays orders the results by the subscription_days field.
func BySubscriptionDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionDays, opts...).ToFunc()
}

// BySubscriptionOriginalExpiresAt orders the results by the subscription_original_expires_at field.
func BySubscriptionOriginalExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionOriginalExpiresAt, opts...).ToFunc()
}

// BySubscriptionOriginalStatus orders the results by the subscription_original_status field.
func BySubscriptionOriginalStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionOriginalStatus, opts...).ToFunc()
}

// BySubscriptionRevoked orders the results by the subscription_revoked field.
func BySubscriptionRevoked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionRevoked, opts...).ToFunc()
}

// ByDeductionState orders the results by the deduction_state field.
func ByDeductionState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeductionState, opts...).ToFunc()
}

// ByProviderRefundID orders the results by the provider_refund_id field.
func ByProviderRefundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderRefundID, opts...).ToFunc()
}

// ByProviderState orders the results by the provider_state field.
func ByProviderState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderState, opts...).ToFunc()
}

// ByProviderResult orders the results by the provider_result field.
func ByProviderResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderResult, opts...).ToFunc()
}

// ByManualReview orders the results by the manual_review field.
func ByManualReview(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualReview, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
