// Code generated by ent, DO NOT EDIT.

package paymentrefundattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldID, id))
}

// AttemptID applies equality check predicate on the "attempt_id" field. It's identical to AttemptIDEQ.
func AttemptID(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldAttemptID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldOrderID, v))
}

// RefundAmount applies equality check predicate on the "refund_amount" field. It's identical to RefundAmountEQ.
func RefundAmount(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldRefundAmount, v))
}

// GatewayAmount applies equality check predicate on the "gateway_amount" field. It's identical to GatewayAmountEQ.
func GatewayAmount(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldGatewayAmount, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldReason, v))
}

// OriginalOrderStatus applies equality check predicate on the "original_order_status" field. It's identical to OriginalOrderStatusEQ.
func OriginalOrderStatus(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldOriginalOrderStatus, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSource, v))
}

// DeductBalance applies equality check predicate on the "deduct_balance" field. It's identical to DeductBalanceEQ.
func DeductBalance(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldDeductBalance, v))
}

// Force applies equality check predicate on the "force" field. It's identical to ForceEQ.
func Force(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldForce, v))
}

// DeductionType applies equality check predicate on the "deduction_type" field. It's identical to DeductionTypeEQ.
func DeductionType(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldDeductionType, v))
}

// HeldBalanceAmount applies equality check predicate on the "held_balance_amount" field. It's identical to HeldBalanceAmountEQ.
func HeldBalanceAmount(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldHeldBalanceAmount, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionDays applies equality check predicate on the "subscription_days" field. It's identical to SubscriptionDaysEQ.
func SubscriptionDays(v int) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionDays, v))
}

// SubscriptionOriginalExpiresAt applies equality check predicate on the "subscription_original_expires_at" field. It's identical to SubscriptionOriginalExpiresAtEQ.
func SubscriptionOriginalExpiresAt(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionOriginalExpiresAt, v))
}

// SubscriptionOriginalStatus applies equality check predicate on the "subscription_original_status" field. It's identical to SubscriptionOriginalStatusEQ.
func SubscriptionOriginalStatus(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionRevoked applies equality check predicate on the "subscription_revoked" field. It's identical to SubscriptionRevokedEQ.
func SubscriptionRevoked(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionRevoked, v))
}

// DeductionState applies equality check predicate on the "deduction_state" field. It's identical to DeductionStateEQ.
func DeductionState(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldDeductionState, v))
}

// ProviderRefundID applies equality check predicate on the "provider_refund_id" field. It's identical to ProviderRefundIDEQ.
func ProviderRefundID(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldProviderRefundID, v))
}

// ProviderState applies equality check predicate on the "provider_state" field. It's identical to ProviderStateEQ.
func ProviderState(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldProviderState, v))
}

// ProviderResult applies equality check predicate on the "provider_result" field. It's identical to ProviderResultEQ.
func ProviderResult(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldProviderResult, v))
}

// ManualReview applies equality check predicate on the "manual_review" field. It's identical to ManualReviewEQ.
func ManualReview(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldManualReview, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldUpdatedAt, v))
}

// AttemptIDEQ applies the EQ predicate on the "attempt_id" field.
func AttemptIDEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldAttemptID, v))
}

// AttemptIDNEQ applies the NEQ predicate on the "attempt_id" field.
func AttemptIDNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldAttemptID, v))
}

// AttemptIDIn applies the In predicate on the "attempt_id" field.
func AttemptIDIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldAttemptID, vs...))
}

// AttemptIDNotIn applies the NotIn predicate on the "attempt_id" field.
func AttemptIDNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldAttemptID, vs...))
}

// AttemptIDGT applies the GT predicate on the "attempt_id" field.
func AttemptIDGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldAttemptID, v))
}

// AttemptIDGTE applies the GTE predicate on the "attempt_id" field.
func AttemptIDGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldAttemptID, v))
}

// AttemptIDLT applies the LT predicate on the "attempt_id" field.
func AttemptIDLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldAttemptID, v))
}

// AttemptIDLTE applies the LTE predicate on the "attempt_id" field.
func AttemptIDLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldAttemptID, v))
}

// AttemptIDContains applies the Contains predicate on the "attempt_id" field.
func AttemptIDContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldAttemptID, v))
}

// AttemptIDHasPrefix applies the HasPrefix predicate on the "attempt_id" field.
func AttemptIDHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldAttemptID, v))
}

// AttemptIDHasSuffix applies the HasSuffix predicate on the "attempt_id" field.
func AttemptIDHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldAttemptID, v))
}

// AttemptIDEqualFold applies the EqualFold predicate on the "attempt_id" field.
func AttemptIDEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldAttemptID, v))
}

// AttemptIDContainsFold applies the ContainsFold predicate on the "attempt_id" field.
func AttemptIDContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldAttemptID, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldOrderID, v))
}

// RefundAmountEQ applies the EQ predicate on the "refund_amount" field.
func RefundAmountEQ(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldRefundAmount, v))
}

// RefundAmountNEQ applies the NEQ predicate on the "refund_amount" field.
func RefundAmountNEQ(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldRefundAmount, v))
}

// RefundAmountIn applies the In predicate on the "refund_amount" field.
func RefundAmountIn(vs ...float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldRefundAmount, vs...))
}

// RefundAmountNotIn applies the NotIn predicate on the "refund_amount" field.
func RefundAmountNotIn(vs ...float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldRefundAmount, vs...))
}

// RefundAmountGT applies the GT predicate on the "refund_amount" field.
func RefundAmountGT(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldRefundAmount, v))
}

// RefundAmountGTE applies the GTE predicate on the "refund_amount" field.
func RefundAmountGTE(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldRefundAmount, v))
}

// RefundAmountLT applies the LT predicate on the "refund_amount" field.
func RefundAmountLT(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldRefundAmount, v))
}

// RefundAmountLTE applies the LTE predicate on the "refund_amount" field.
func RefundAmountLTE(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldRefundAmount, v))
}

// GatewayAmountEQ applies the EQ predicate on the "gateway_amount" field.
func GatewayAmountEQ(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldGatewayAmount, v))
}

// GatewayAmountNEQ applies the NEQ predicate on the "gateway_amount" field.
func GatewayAmountNEQ(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldGatewayAmount, v))
}

// GatewayAmountIn applies the In predicate on the "gateway_amount" field.
func GatewayAmountIn(vs ...float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldGatewayAmount, vs...))
}

// GatewayAmountNotIn applies the NotIn predicate on the "gateway_amount" field.
func GatewayAmountNotIn(vs ...float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldGatewayAmount, vs...))
}

// GatewayAmountGT applies the GT predicate on the "gateway_amount" field.
func GatewayAmountGT(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldGatewayAmount, v))
}

// GatewayAmountGTE applies the GTE predicate on the "gateway_amount" field.
func GatewayAmountGTE(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldGatewayAmount, v))
}

// GatewayAmountLT applies the LT predicate on the "gateway_amount" field.
func GatewayAmountLT(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldGatewayAmount, v))
}

// GatewayAmountLTE applies the LTE predicate on the "gateway_amount" field.
func GatewayAmountLTE(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldGatewayAmount, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldReason, v))
}

// OriginalOrderStatusEQ applies the EQ predicate on the "original_order_status" field.
func OriginalOrderStatusEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusNEQ applies the NEQ predicate on the "original_order_status" field.
func OriginalOrderStatusNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusIn applies the In predicate on the "original_order_status" field.
func OriginalOrderStatusIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldOriginalOrderStatus, vs...))
}

// OriginalOrderStatusNotIn applies the NotIn predicate on the "original_order_status" field.
func OriginalOrderStatusNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldOriginalOrderStatus, vs...))
}

// OriginalOrderStatusGT applies the GT predicate on the "original_order_status" field.
func OriginalOrderStatusGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusGTE applies the GTE predicate on the "original_order_status" field.
func OriginalOrderStatusGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusLT applies the LT predicate on the "original_order_status" field.
func OriginalOrderStatusLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusLTE applies the LTE predicate on the "original_order_status" field.
func OriginalOrderStatusLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusContains applies the Contains predicate on the "original_order_status" field.
func OriginalOrderStatusContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusHasPrefix applies the HasPrefix predicate on the "original_order_status" field.
func OriginalOrderStatusHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusHasSuffix applies the HasSuffix predicate on the "original_order_status" field.
func OriginalOrderStatusHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusEqualFold applies the EqualFold predicate on the "original_order_status" field.
func OriginalOrderStatusEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldOriginalOrderStatus, v))
}

// OriginalOrderStatusContainsFold applies the ContainsFold predicate on the "original_order_status" field.
func OriginalOrderStatusContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldOriginalOrderStatus, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldSource, v))
}

// DeductBalanceEQ applies the EQ predicate on the "deduct_balance" field.
func DeductBalanceEQ(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldDeductBalance, v))
}

// DeductBalanceNEQ applies the NEQ predicate on the "deduct_balance" field.
func DeductBalanceNEQ(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldDeductBalance, v))
}

// ForceEQ applies the EQ predicate on the "force" field.
func ForceEQ(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldForce, v))
}

// ForceNEQ applies the NEQ predicate on the "force" field.
func ForceNEQ(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldForce, v))
}

// DeductionTypeEQ applies the EQ predicate on the "deduction_type" field.
func DeductionTypeEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldDeductionType, v))
}

// DeductionTypeNEQ applies the NEQ predicate on the "deduction_type" field.
func DeductionTypeNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldDeductionType, v))
}

// DeductionTypeIn applies the In predicate on the "deduction_type" field.
func DeductionTypeIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldDeductionType, vs...))
}

// DeductionTypeNotIn applies the NotIn predicate on the "deduction_type" field.
func DeductionTypeNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldDeductionType, vs...))
}

// DeductionTypeGT applies the GT predicate on the "deduction_type" field.
func DeductionTypeGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldDeductionType, v))
}

// DeductionTypeGTE applies the GTE predicate on the "deduction_type" field.
func DeductionTypeGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldDeductionType, v))
}

// DeductionTypeLT applies the LT predicate on the "deduction_type" field.
func DeductionTypeLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldDeductionType, v))
}

// DeductionTypeLTE applies the LTE predicate on the "deduction_type" field.
func DeductionTypeLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldDeductionType, v))
}

// DeductionTypeContains applies the Contains predicate on the "deduction_type" field.
func DeductionTypeContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldDeductionType, v))
}

// DeductionTypeHasPrefix applies the HasPrefix predicate on the "deduction_type" field.
func DeductionTypeHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldDeductionType, v))
}

// DeductionTypeHasSuffix applies the HasSuffix predicate on the "deduction_type" field.
func DeductionTypeHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldDeductionType, v))
}

// DeductionTypeEqualFold applies the EqualFold predicate on the "deduction_type" field.
func DeductionTypeEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldDeductionType, v))
}

// DeductionTypeContainsFold applies the ContainsFold predicate on the "deduction_type" field.
func DeductionTypeContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldDeductionType, v))
}

// HeldBalanceAmountEQ applies the EQ predicate on the "held_balance_amount" field.
func HeldBalanceAmountEQ(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldHeldBalanceAmount, v))
}

// HeldBalanceAmountNEQ applies the NEQ predicate on the "held_balance_amount" field.
func HeldBalanceAmountNEQ(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldHeldBalanceAmount, v))
}

// HeldBalanceAmountIn applies the In predicate on the "held_balance_amount" field.
func HeldBalanceAmountIn(vs ...float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldHeldBalanceAmount, vs...))
}

// HeldBalanceAmountNotIn applies the NotIn predicate on the "held_balance_amount" field.
func HeldBalanceAmountNotIn(vs ...float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldHeldBalanceAmount, vs...))
}

// HeldBalanceAmountGT applies the GT predicate on the "held_balance_amount" field.
func HeldBalanceAmountGT(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldHeldBalanceAmount, v))
}

// HeldBalanceAmountGTE applies the GTE predicate on the "held_balance_amount" field.
func HeldBalanceAmountGTE(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldHeldBalanceAmount, v))
}

// HeldBalanceAmountLT applies the LT predicate on the "held_balance_amount" field.
func HeldBalanceAmountLT(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldHeldBalanceAmount, v))
}

// HeldBalanceAmountLTE applies the LTE predicate on the "held_balance_amount" field.
func HeldBalanceAmountLTE(v float64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldHeldBalanceAmount, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v int64) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldSubscriptionID, v))
}

// SubscriptionIDIsNil applies the IsNil predicate on the "subscription_id" field.
func SubscriptionIDIsNil() predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIsNull(FieldSubscriptionID))
}

// SubscriptionIDNotNil applies the NotNil predicate on the "subscription_id" field.
func SubscriptionIDNotNil() predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotNull(FieldSubscriptionID))
}

// SubscriptionDaysEQ applies the EQ predicate on the "subscription_days" field.
func SubscriptionDaysEQ(v int) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionDays, v))
}

// SubscriptionDaysNEQ applies the NEQ predicate on the "subscription_days" field.
func SubscriptionDaysNEQ(v int) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldSubscriptionDays, v))
}

// SubscriptionDaysIn applies the In predicate on the "subscription_days" field.
func SubscriptionDaysIn(vs ...int) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldSubscriptionDays, vs...))
}

// SubscriptionDaysNotIn applies the NotIn predicate on the "subscription_days" field.
func SubscriptionDaysNotIn(vs ...int) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldSubscriptionDays, vs...))
}

// SubscriptionDaysGT applies the GT predicate on the "subscription_days" field.
func SubscriptionDaysGT(v int) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldSubscriptionDays, v))
}

// SubscriptionDaysGTE applies the GTE predicate on the "subscription_days" field.
func SubscriptionDaysGTE(v int) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldSubscriptionDays, v))
}

// SubscriptionDaysLT applies the LT predicate on the "subscription_days" field.
func SubscriptionDaysLT(v int) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldSubscriptionDays, v))
}

// SubscriptionDaysLTE applies the LTE predicate on the "subscription_days" field.
func SubscriptionDaysLTE(v int) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldSubscriptionDays, v))
}

// SubscriptionOriginalExpiresAtEQ applies the EQ predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtEQ(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionOriginalExpiresAt, v))
}

// SubscriptionOriginalExpiresAtNEQ applies the NEQ predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtNEQ(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldSubscriptionOriginalExpiresAt, v))
}

// SubscriptionOriginalExpiresAtIn applies the In predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtIn(vs ...time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldSubscriptionOriginalExpiresAt, vs...))
}

// SubscriptionOriginalExpiresAtNotIn applies the NotIn predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtNotIn(vs ...time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldSubscriptionOriginalExpiresAt, vs...))
}

// SubscriptionOriginalExpiresAtGT applies the GT predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtGT(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldSubscriptionOriginalExpiresAt, v))
}

// SubscriptionOriginalExpiresAtGTE applies the GTE predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtGTE(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldSubscriptionOriginalExpiresAt, v))
}

// SubscriptionOriginalExpiresAtLT applies the LT predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtLT(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldSubscriptionOriginalExpiresAt, v))
}

// SubscriptionOriginalExpiresAtLTE applies the LTE predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtLTE(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldSubscriptionOriginalExpiresAt, v))
}

// SubscriptionOriginalExpiresAtIsNil applies the IsNil predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtIsNil() predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIsNull(FieldSubscriptionOriginalExpiresAt))
}

// SubscriptionOriginalExpiresAtNotNil applies the NotNil predicate on the "subscription_original_expires_at" field.
func SubscriptionOriginalExpiresAtNotNil() predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotNull(FieldSubscriptionOriginalExpiresAt))
}

// SubscriptionOriginalStatusEQ applies the EQ predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusNEQ applies the NEQ predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusIn applies the In predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldSubscriptionOriginalStatus, vs...))
}

// SubscriptionOriginalStatusNotIn applies the NotIn predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldSubscriptionOriginalStatus, vs...))
}

// SubscriptionOriginalStatusGT applies the GT predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusGTE applies the GTE predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusLT applies the LT predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusLTE applies the LTE predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusContains applies the Contains predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusHasPrefix applies the HasPrefix predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusHasSuffix applies the HasSuffix predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusIsNil applies the IsNil predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusIsNil() predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIsNull(FieldSubscriptionOriginalStatus))
}

// SubscriptionOriginalStatusNotNil applies the NotNil predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusNotNil() predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotNull(FieldSubscriptionOriginalStatus))
}

// SubscriptionOriginalStatusEqualFold applies the EqualFold predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionOriginalStatusContainsFold applies the ContainsFold predicate on the "subscription_original_status" field.
func SubscriptionOriginalStatusContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldSubscriptionOriginalStatus, v))
}

// SubscriptionRevokedEQ applies the EQ predicate on the "subscription_revoked" field.
func SubscriptionRevokedEQ(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldSubscriptionRevoked, v))
}

// SubscriptionRevokedNEQ applies the NEQ predicate on the "subscription_revoked" field.
func SubscriptionRevokedNEQ(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldSubscriptionRevoked, v))
}

// DeductionStateEQ applies the EQ predicate on the "deduction_state" field.
func DeductionStateEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldDeductionState, v))
}

// DeductionStateNEQ applies the NEQ predicate on the "deduction_state" field.
func DeductionStateNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldDeductionState, v))
}

// DeductionStateIn applies the In predicate on the "deduction_state" field.
func DeductionStateIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldDeductionState, vs...))
}

// DeductionStateNotIn applies the NotIn predicate on the "deduction_state" field.
func DeductionStateNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldDeductionState, vs...))
}

// DeductionStateGT applies the GT predicate on the "deduction_state" field.
func DeductionStateGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldDeductionState, v))
}

// DeductionStateGTE applies the GTE predicate on the "deduction_state" field.
func DeductionStateGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldDeductionState, v))
}

// DeductionStateLT applies the LT predicate on the "deduction_state" field.
func DeductionStateLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldDeductionState, v))
}

// DeductionStateLTE applies the LTE predicate on the "deduction_state" field.
func DeductionStateLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldDeductionState, v))
}

// DeductionStateContains applies the Contains predicate on the "deduction_state" field.
func DeductionStateContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldDeductionState, v))
}

// DeductionStateHasPrefix applies the HasPrefix predicate on the "deduction_state" field.
func DeductionStateHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldDeductionState, v))
}

// DeductionStateHasSuffix applies the HasSuffix predicate on the "deduction_state" field.
func DeductionStateHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldDeductionState, v))
}

// DeductionStateEqualFold applies the EqualFold predicate on the "deduction_state" field.
func DeductionStateEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldDeductionState, v))
}

// DeductionStateContainsFold applies the ContainsFold predicate on the "deduction_state" field.
func DeductionStateContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldDeductionState, v))
}

// ProviderRefundIDEQ applies the EQ predicate on the "provider_refund_id" field.
func ProviderRefundIDEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldProviderRefundID, v))
}

// ProviderRefundIDNEQ applies the NEQ predicate on the "provider_refund_id" field.
func ProviderRefundIDNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldProviderRefundID, v))
}

// ProviderRefundIDIn applies the In predicate on the "provider_refund_id" field.
func ProviderRefundIDIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldProviderRefundID, vs...))
}

// ProviderRefundIDNotIn applies the NotIn predicate on the "provider_refund_id" field.
func ProviderRefundIDNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldProviderRefundID, vs...))
}

// ProviderRefundIDGT applies the GT predicate on the "provider_refund_id" field.
func ProviderRefundIDGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldProviderRefundID, v))
}

// ProviderRefundIDGTE applies the GTE predicate on the "provider_refund_id" field.
func ProviderRefundIDGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldProviderRefundID, v))
}

// ProviderRefundIDLT applies the LT predicate on the "provider_refund_id" field.
func ProviderRefundIDLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldProviderRefundID, v))
}

// ProviderRefundIDLTE applies the LTE predicate on the "provider_refund_id" field.
func ProviderRefundIDLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldProviderRefundID, v))
}

// ProviderRefundIDContains applies the Contains predicate on the "provider_refund_id" field.
func ProviderRefundIDContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldProviderRefundID, v))
}

// ProviderRefundIDHasPrefix applies the HasPrefix predicate on the "provider_refund_id" field.
func ProviderRefundIDHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldProviderRefundID, v))
}

// ProviderRefundIDHasSuffix applies the HasSuffix predicate on the "provider_refund_id" field.
func ProviderRefundIDHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldProviderRefundID, v))
}

// ProviderRefundIDIsNil applies the IsNil predicate on the "provider_refund_id" field.
func ProviderRefundIDIsNil() predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIsNull(FieldProviderRefundID))
}

// ProviderRefundIDNotNil applies the NotNil predicate on the "provider_refund_id" field.
func ProviderRefundIDNotNil() predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotNull(FieldProviderRefundID))
}

// ProviderRefundIDEqualFold applies the EqualFold predicate on the "provider_refund_id" field.
func ProviderRefundIDEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldProviderRefundID, v))
}

// ProviderRefundIDContainsFold applies the ContainsFold predicate on the "provider_refund_id" field.
func ProviderRefundIDContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldProviderRefundID, v))
}

// ProviderStateEQ applies the EQ predicate on the "provider_state" field.
func ProviderStateEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldProviderState, v))
}

// ProviderStateNEQ applies the NEQ predicate on the "provider_state" field.
func ProviderStateNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldProviderState, v))
}

// ProviderStateIn applies the In predicate on the "provider_state" field.
func ProviderStateIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldProviderState, vs...))
}

// ProviderStateNotIn applies the NotIn predicate on the "provider_state" field.
func ProviderStateNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldProviderState, vs...))
}

// ProviderStateGT applies the GT predicate on the "provider_state" field.
func ProviderStateGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldProviderState, v))
}

// ProviderStateGTE applies the GTE predicate on the "provider_state" field.
func ProviderStateGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldProviderState, v))
}

// ProviderStateLT applies the LT predicate on the "provider_state" field.
func ProviderStateLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldProviderState, v))
}

// ProviderStateLTE applies the LTE predicate on the "provider_state" field.
func ProviderStateLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldProviderState, v))
}

// ProviderStateContains applies the Contains predicate on the "provider_state" field.
func ProviderStateContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldProviderState, v))
}

// ProviderStateHasPrefix applies the HasPrefix predicate on the "provider_state" field.
func ProviderStateHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldProviderState, v))
}

// ProviderStateHasSuffix applies the HasSuffix predicate on the "provider_state" field.
func ProviderStateHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldProviderState, v))
}

// ProviderStateEqualFold applies the EqualFold predicate on the "provider_state" field.
func ProviderStateEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldProviderState, v))
}

// ProviderStateContainsFold applies the ContainsFold predicate on the "provider_state" field.
func ProviderStateContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldProviderState, v))
}

// ProviderResultEQ applies the EQ predicate on the "provider_result" field.
func ProviderResultEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldProviderResult, v))
}

// ProviderResultNEQ applies the NEQ predicate on the "provider_result" field.
func ProviderResultNEQ(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldProviderResult, v))
}

// ProviderResultIn applies the In predicate on the "provider_result" field.
func ProviderResultIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldProviderResult, vs...))
}

// ProviderResultNotIn applies the NotIn predicate on the "provider_result" field.
func ProviderResultNotIn(vs ...string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldProviderResult, vs...))
}

// ProviderResultGT applies the GT predicate on the "provider_result" field.
func ProviderResultGT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldProviderResult, v))
}

// ProviderResultGTE applies the GTE predicate on the "provider_result" field.
func ProviderResultGTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldProviderResult, v))
}

// ProviderResultLT applies the LT predicate on the "provider_result" field.
func ProviderResultLT(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldProviderResult, v))
}

// ProviderResultLTE applies the LTE predicate on the "provider_result" field.
func ProviderResultLTE(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldProviderResult, v))
}

// ProviderResultContains applies the Contains predicate on the "provider_result" field.
func ProviderResultContains(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContains(FieldProviderResult, v))
}

// ProviderResultHasPrefix applies the HasPrefix predicate on the "provider_result" field.
func ProviderResultHasPrefix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasPrefix(FieldProviderResult, v))
}

// ProviderResultHasSuffix applies the HasSuffix predicate on the "provider_result" field.
func ProviderResultHasSuffix(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldHasSuffix(FieldProviderResult, v))
}

// ProviderResultEqualFold applies the EqualFold predicate on the "provider_result" field.
func ProviderResultEqualFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEqualFold(FieldProviderResult, v))
}

// ProviderResultContainsFold applies the ContainsFold predicate on the "provider_result" field.
func ProviderResultContainsFold(v string) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldContainsFold(FieldProviderResult, v))
}

// ManualReviewEQ applies the EQ predicate on the "manual_review" field.
func ManualReviewEQ(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldManualReview, v))
}

// ManualReviewNEQ applies the NEQ predicate on the "manual_review" field.
func ManualReviewNEQ(v bool) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldManualReview, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentRefundAttempt) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentRefundAttempt) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentRefundAttempt) predicate.PaymentRefundAttempt {
	return predicate.PaymentRefundAttempt(sql.NotPredicates(p))
}
